services:
  web:
    image: harbor.mppe.mp.br/dempam/sipat:2026.3.16102254-6c9c05c
    ports:
      - "8000:8000"
    env_file:
      - .env
    volumes:
      - .:/app
    depends_on:
      - db


  db:
    image: postgres:16
    environment:
      POSTGRES_DB: sipat
      POSTGRES_USER: sipat
      POSTGRES_PASSWORD: sipat
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: