# Generated by Django 6.0.2 on 2026-02-23 18:45

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CircunscricaoPredio',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('local', models.CharField(max_length=80, verbose_name='Local')),
            ],
            options={
                'verbose_name': 'Circunscrição/Prédio',
                'verbose_name_plural': 'Circunscrições/Prédios',
            },
        ),
        migrations.CreateModel(
            name='SetorDEMPAM',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('setor', models.CharField(max_length=30, verbose_name='Setor/Sala')),
            ],
            options={
                'verbose_name': 'Setor/Sala DEMPAM',
                'verbose_name_plural': 'Setores/Salas DEMPAM',
            },
        ),
        migrations.CreateModel(
            name='InfoUA',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('ua', models.CharField(max_length=100, verbose_name='UA')),
                ('contato_ua', models.CharField(blank=True, max_length=15, null=True, validators=[django.core.validators.RegexValidator(regex='^\\+?\\d{10,15}$')], verbose_name='Contato da UA')),
                ('responsavel_ua', models.CharField(blank=True, default='Não Consta', max_length=60, verbose_name='Responsável da UA')),
                ('mat_resp_ua', models.IntegerField(blank=True, null=True, verbose_name='Matrícula do Responsável da UA')),
                ('email_ua', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email da UA')),
                ('circunscricao_predio', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='circunscricoes_predios', to='dempam.circunscricaopredio', verbose_name='Circunscricao/Prédio')),
            ],
            options={
                'verbose_name': 'UA',
                'verbose_name_plural': 'UAs',
            },
        ),
        migrations.CreateModel(
            name='LocalizacaoDEMPAM',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('prateleira_pallet', models.CharField(blank=True, max_length=30, null=True, verbose_name='Prateleira/Pallet')),
                ('tipo_localizacao', models.CharField(blank=True, choices=[('PALLET', 'Pallet'), ('PRATELEIRA', 'Prateleira')], max_length=30, null=True)),
                ('setor_sala', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='localizacao_interna', to='dempam.setordempam', verbose_name='Setor/Sala')),
            ],
            options={
                'verbose_name': 'Localização DEMPAM',
                'verbose_name_plural': 'Localizações DEMPAM',
            },
        ),
    ]
