# Generated by Django 6.0.2 on 2026-02-23 20:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dempam', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='circunscricaopredio',
            options={'verbose_name': 'Circunscrição/Prédio', 'verbose_name_plural': '01 - Circunscrições/Prédios'},
        ),
        migrations.AlterModelOptions(
            name='infoua',
            options={'verbose_name': 'UA', 'verbose_name_plural': '02 - UAs'},
        ),
        migrations.AlterModelOptions(
            name='localizacaodempam',
            options={'verbose_name': 'Localização DEMPAM', 'verbose_name_plural': '04 - Localizações DEMPAM'},
        ),
        migrations.AlterModelOptions(
            name='setordempam',
            options={'verbose_name': 'Setor/Sala DEMPAM', 'verbose_name_plural': '03 - Setores/Salas DEMPAM'},
        ),
    ]
