# Generated by Django 6.0.2 on 2026-03-02 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dempam', '0002_alter_circunscricaopredio_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='circunscricaopredio',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='infoua',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='localizacaodempam',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='setordempam',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
