# Generated by Django 6.0.2 on 2026-06-18 20:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dempam', '0002_infoua_gestor'),
    ]

    operations = [
        migrations.AddField(
            model_name='infoua',
            name='codigo',
            field=models.CharField(blank=True, max_length=12, null=True, unique=True, verbose_name='Código'),
        ),
        migrations.AddField(
            model_name='infoua',
            name='nivel',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Nível'),
        ),
        migrations.AddField(
            model_name='infoua',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='filhas', to='dempam.infoua', verbose_name='UA Pai'),
        ),
        migrations.AddField(
            model_name='infoua',
            name='sigla',
            field=models.CharField(blank=True, max_length=30, verbose_name='Sigla'),
        ),
    ]
