# Generated by Django 6.0.2 on 2026-07-23 16:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dempam', '0003_infoua_codigo_infoua_nivel_infoua_parent_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Aviso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=120, verbose_name='Título')),
                ('mensagem', models.TextField(verbose_name='Mensagem')),
                ('data_publicacao', models.DateTimeField(auto_now_add=True, verbose_name='Publicado em')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('autor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='avisos_publicados', to=settings.AUTH_USER_MODEL, verbose_name='Autor')),
            ],
            options={
                'verbose_name': 'Aviso',
                'verbose_name_plural': '05 - Avisos',
                'ordering': ['-data_publicacao'],
            },
        ),
    ]
