# Generated by Django 6.0.2 on 2026-07-28 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dempam', '0004_aviso'),
    ]

    operations = [
        migrations.AddField(
            model_name='localizacaodempam',
            name='corredor',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Corredor'),
        ),
        migrations.AddField(
            model_name='localizacaodempam',
            name='estante',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Estante'),
        ),
        migrations.AddField(
            model_name='localizacaodempam',
            name='prateleira',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Prateleira'),
        ),
    ]
