# Generated by Django 6.0.2 on 2026-07-30 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dempam', '0006_configuracaopaineltv'),
    ]

    operations = [
        migrations.AddField(
            model_name='aviso',
            name='exibir_ate',
            field=models.DateTimeField(blank=True, help_text='Deixe em branco para não expirar automaticamente.', null=True, verbose_name='Exibir até'),
        ),
        migrations.AddField(
            model_name='aviso',
            name='exibir_de',
            field=models.DateTimeField(blank=True, help_text='Deixe em branco para exibir imediatamente.', null=True, verbose_name='Exibir a partir de'),
        ),
    ]
