# Generated by Django 6.0.2 on 2026-07-30 13:23

import dempam.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dempam', '0007_aviso_exibir_ate_aviso_exibir_de'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuracaopaineltv',
            name='video_arquivo',
            field=models.FileField(blank=True, help_text='Se enviado, tem prioridade sobre o link acima.', null=True, upload_to=dempam.utils.path_video_painel_tv, verbose_name='Arquivo de vídeo'),
        ),
        migrations.AlterField(
            model_name='configuracaopaineltv',
            name='video_url',
            field=models.URLField(blank=True, null=True, verbose_name='Link do vídeo (YouTube ou link direto)'),
        ),
    ]
