# Generated by Django 6.0.2 on 2026-08-14 17:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dempam', '0008_configuracaopaineltv_video_arquivo_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Municipio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, unique=True, verbose_name='Município')),
                ('codigo_ibge', models.CharField(max_length=10, unique=True, verbose_name='Código IBGE')),
            ],
            options={
                'verbose_name': 'Município',
                'verbose_name_plural': '01b - Municípios',
                'ordering': ['nome'],
            },
        ),
        migrations.AddField(
            model_name='infoua',
            name='municipio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uas', to='dempam.municipio', verbose_name='Município'),
        ),
    ]
