# Generated by Django 6.0.2 on 2026-08-14 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dempam', '0009_municipio_infoua_municipio'),
    ]

    operations = [
        migrations.AddField(
            model_name='municipio',
            name='circunscricao',
            field=models.CharField(blank=True, max_length=60, verbose_name='Circunscrição'),
        ),
    ]
