# Generated by Django 6.0.2 on 2026-08-17 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dempam', '0010_municipio_circunscricao'),
    ]

    operations = [
        migrations.AddField(
            model_name='setordempam',
            name='tipo',
            field=models.CharField(choices=[('DIMMS', 'DIMMS — Bens de Consumo'), ('DIMRCBP', 'DIMRCBP — Bens Permanentes')], default='DIMMS', max_length=10, verbose_name='Tipo'),
        ),
    ]
