# Generated by Django 6.0.2 on 2026-03-26 13:19

import dimms.utils
import django.core.validators
import django.db.models.deletion
import localflavor.br.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('dempam', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BensConsumo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('efisco', models.CharField(blank=True, default='Não Consta', max_length=20, verbose_name='E-Fisco')),
                ('descricao_efisco', models.TextField(blank=True, null=True, verbose_name='Descrição Efisco')),
                ('medida', models.CharField(blank=True, choices=[('METRO', 'Metro'), ('UNIDADE', 'Unidade'), ('QUILOGRAMA', 'Quilograma'), ('LITRO', 'Litro'), ('PACOTE', 'Pacote'), ('CAIXA', 'Caixa')], max_length=20, null=True, verbose_name='Unidade de Medida')),
                ('grupo_consumo', models.CharField(blank=True, choices=[('ALIMENTO', 'Alimento'), ('CONFECCAO', 'Confecção'), ('COPA_COZINHA', 'Copa / Cozinha'), ('DOMISSANITARIO', 'Domissanitário'), ('ELETRICA', 'Elétrica'), ('EPI', 'EPI'), ('HIDROSANITARIO', 'Hidrossanitário'), ('INFORMATICA', 'Informática'), ('LIMPEZA', 'Limpeza'), ('MANUTENCAO', 'Manutenção'), ('MARCENARIA', 'Marcenaria'), ('PINTURA', 'Pintura'), ('PAPEIS_EXPEDIENTE', 'Papéis de Expediente'), ('PAPEIS_LIMPEZA', 'Papéis de Limpeza'), ('REFRIGERACAO', 'Refrigeração'), ('TONER', 'Toner')], null=True, verbose_name='Grupo')),
            ],
            options={
                'verbose_name': 'Bem de Consumo',
                'verbose_name_plural': '01 - Bens de Consumo',
            },
        ),
        migrations.CreateModel(
            name='Contrato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contrato', models.CharField(max_length=30, verbose_name='N° Contrato')),
                ('inicio_vigencia', models.DateField(blank=True, null=True, verbose_name='Início da Vigência')),
                ('final_vigencia', models.DateField(blank=True, null=True, verbose_name='Final da Vigência')),
                ('homologacao', models.DateField(blank=True, null=True, verbose_name='Homologação')),
                ('cs', models.IntegerField(blank=True, null=True, verbose_name='N° CS')),
                ('cod_liquidacao', models.IntegerField(blank=True, null=True, verbose_name='Código de Licitação')),
                ('status', models.CharField(blank=True, max_length=20, null=True, verbose_name='Status do Contrato')),
            ],
            options={
                'verbose_name': 'Contrato',
                'verbose_name_plural': '03 - Contratos',
            },
        ),
        migrations.CreateModel(
            name='ItensSolicitados',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.PositiveIntegerField(blank=True, null=True, verbose_name='Quantidade Solicitada')),
            ],
            options={
                'verbose_name': 'Bens Solicitado',
                'verbose_name_plural': '06 - Bens Solicitados',
            },
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('supplier', models.CharField(max_length=40, verbose_name='Fornecedor')),
                ('cnpj_supplier', localflavor.br.models.BRCNPJField(blank=True, max_length=18, null=True, verbose_name='CNPJ do Fornecedor')),
                ('name_responsible', models.CharField(blank=True, max_length=90, verbose_name='Nome do Responsável')),
                ('cpf_responsible', localflavor.br.models.BRCPFField(blank=True, max_length=14, verbose_name='Cpf do Responsável')),
                ('contact_supplier', models.CharField(blank=True, max_length=15, null=True, validators=[django.core.validators.RegexValidator(regex='^\\+?\\d{10,15}$')], verbose_name='Contato do Fornecedor')),
                ('email_supplier', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email do Fornecedor')),
            ],
            options={
                'verbose_name': 'Fornecedor',
                'verbose_name_plural': '02 - Fonecedores',
            },
        ),
        migrations.CreateModel(
            name='Artifacts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('artifacts_code', models.CharField(blank=True, editable=False, max_length=50, unique=True, verbose_name='Artefato')),
                ('description', models.CharField(blank=True, max_length=100, verbose_name='Descrição')),
                ('sei', models.CharField(blank=True, max_length=50, verbose_name='SEI')),
                ('tr', models.FileField(blank=True, upload_to=dimms.utils.path_tr, verbose_name='(TR) Termo de Referência')),
                ('etp', models.FileField(blank=True, upload_to=dimms.utils.path_etp, verbose_name='(ETP) Estudo Técnico Preeliminar')),
                ('rgpp', models.FileField(blank=True, upload_to=dimms.utils.path_rgpp, verbose_name='(RGPP) Registro de Preço')),
                ('dode', models.FileField(blank=True, upload_to=dimms.utils.path_dode, verbose_name='(DODE)Documento de Oficialização de Demanda')),
                ('tapp', models.FileField(blank=True, upload_to=dimms.utils.path_tapp, verbose_name='(TAPP) TERMO DE ANALISE PREELIMINAR DO PLANEJAMENTO DA CONTRATAÇÃO')),
                ('risk_analysis', models.FileField(blank=True, upload_to=dimms.utils.path_risk_analysis, verbose_name='Análise de Risco')),
                ('state', models.CharField(blank=True, choices=[('ELABORACAO', 'Em Elaboração'), ('COMPRAS', 'Encaminhado para GMEC'), ('REENCAMINHADO', 'Reencaminhado para Elaboração'), ('LICITACAO', 'Em Licitação'), ('ANALISE', 'Em Análise das Propostas'), ('VENCEDORA', 'Encaminhado Vencedora'), ('HOMOLOGADO', 'Homologado')], max_length=40, verbose_name='Estado')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última modificação')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='artifacts_updated', to=settings.AUTH_USER_MODEL, verbose_name='Última edição por')),
            ],
            options={
                'verbose_name': 'Artefato',
                'verbose_name_plural': 'Artefatos',
            },
        ),
        migrations.CreateModel(
            name='Estoque',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description_manual', models.CharField(max_length=90, verbose_name='Descrição Manual')),
                ('mark', models.CharField(max_length=40, verbose_name='Marca')),
                ('amount_shock', models.PositiveIntegerField(verbose_name='Quantidade')),
                ('monthly_consumption', models.PositiveIntegerField(blank=True, null=True, verbose_name='Consumo Mensal')),
                ('essential', models.BooleanField(blank=True, default=False, verbose_name='Essencial')),
                ('validity', models.DateField(blank=True, null=True, verbose_name='Validade')),
                ('photo', models.ImageField(blank=True, null=True, upload_to=dimms.utils.path_photo_bens, verbose_name='Foto do Item')),
                ('form_input', models.CharField(blank=True, max_length=30, verbose_name='Forma de Entrada')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='Última modificação')),
                ('method', models.CharField(blank=True, max_length=60, verbose_name='Método de Entrada')),
                ('item_shock', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bem_estoque', to='dimms.bensconsumo', verbose_name='Bem no Estoque')),
                ('locate', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='localizacao_consumo', to='dempam.localizacaodempam', verbose_name='Localização')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stock_updated', to=settings.AUTH_USER_MODEL, verbose_name='Última edição por')),
            ],
            options={
                'verbose_name': 'Bem Estoque',
                'verbose_name_plural': '08 - Bens Estoque',
            },
        ),
        migrations.CreateModel(
            name='ItensArtifacts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('details', models.TextField(blank=True, verbose_name='Detalhamento do Item')),
                ('amount', models.PositiveIntegerField(blank=True, verbose_name='Quantidade')),
                ('value_max', models.PositiveIntegerField(blank=True, verbose_name='Valor Máximo')),
                ('artifacts', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='dimms.artifacts', verbose_name='Itens do Artefato')),
                ('efisco', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, to='dimms.bensconsumo', verbose_name='Efisco')),
            ],
            options={
                'verbose_name': 'Item Artefato',
                'verbose_name_plural': 'Itens Artefatos',
            },
        ),
        migrations.CreateModel(
            name='BensEnviados',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade_enviada', models.PositiveIntegerField(blank=True, null=True, verbose_name='Quantidade Enviada')),
                ('data_envio', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Data/Hora do Envio')),
                ('item_enviado', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='itemenviado', to='dimms.itenssolicitados', verbose_name='Bens Enviados')),
            ],
            options={
                'verbose_name': 'Item Enviado',
                'verbose_name_plural': '07 - Bens Enviados',
            },
        ),
        migrations.CreateModel(
            name='Proposal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('proposal_code', models.CharField(blank=True, editable=False, max_length=50, unique=True, verbose_name='Proposta')),
                ('state', models.CharField(blank=True, choices=[('ANALISE', 'Em Análise'), ('APROVADO', 'Aprovado'), ('RECUSADO', 'Recusado')], max_length=30, verbose_name='Estado')),
                ('artifacts_proposal', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='dimms.artifacts', verbose_name='Artefato')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='dimms.supplier', verbose_name='Fornecedor')),
            ],
            options={
                'verbose_name': 'Proposta',
                'verbose_name_plural': 'Propostas',
            },
        ),
        migrations.CreateModel(
            name='ItensProposal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('details_proposal', models.TextField(verbose_name='Detalhes da Proposta')),
                ('amount', models.PositiveIntegerField(verbose_name='Quantidade')),
                ('value', models.PositiveIntegerField(verbose_name='Valor')),
                ('state', models.CharField(blank=True, choices=[('ANALISE', 'Em Análise'), ('APROVADO', 'Aprovado'), ('RECUSADO', 'Recusado')], max_length=50, verbose_name='Status')),
                ('reason', models.TextField(blank=True, verbose_name='Motivo da Reprovação')),
                ('item', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='dimms.itensartifacts', verbose_name='Item')),
                ('proposal_item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='dimms.proposal', verbose_name='Proposta')),
            ],
            options={
                'verbose_name': 'Item Proposta',
                'verbose_name_plural': 'Itens Propostas',
            },
        ),
        migrations.CreateModel(
            name='SaldoAtivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marca', models.CharField(blank=True, max_length=60, null=True, verbose_name='Marca')),
                ('descricao_manual', models.CharField(blank=True, max_length=60, null=True, verbose_name='Descrição Manual')),
                ('quantidade_contrato', models.PositiveIntegerField(verbose_name='Quantidade Contrato')),
                ('saldo_disponivel', models.PositiveIntegerField(blank=True, null=True, verbose_name='Saldo Disponível')),
                ('cota', models.CharField(blank=True, choices=[('PRINCIPAL', 'Principal'), ('RESERVADA', 'Reservada')], max_length=15, null=True, verbose_name='Cota')),
                ('contrato_saldo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='Contrato', to='dimms.contrato', verbose_name='Contrato')),
                ('efisco', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='saldos_ativos', to='dimms.bensconsumo', verbose_name='Efisco')),
            ],
            options={
                'verbose_name': 'Saldo Ativo',
                'verbose_name_plural': '04 - Saldo Ativo',
                'unique_together': {('contrato_saldo', 'efisco')},
            },
        ),
        migrations.AddField(
            model_name='itenssolicitados',
            name='bem',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='itens_enviados', to='dimms.saldoativo', verbose_name='Item do Contrato (Saldo Ativo)'),
        ),
        migrations.CreateModel(
            name='Solicitacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_code', models.CharField(editable=False, max_length=30, unique=True, verbose_name='Código da Solicitação')),
                ('user_order', models.CharField(blank=True, max_length=40, null=True, verbose_name='Usuário Solicitante')),
                ('data_order', models.DateTimeField(auto_now_add=True, verbose_name='Data e Hora da Movimentação')),
                ('observation_order', models.TextField(blank=True, null=True, verbose_name='Observação')),
                ('documents_order', models.FileField(blank=True, null=True, upload_to=dimms.utils.path_solicitation, verbose_name='Documento Anexado')),
                ('stock_deducted', models.BooleanField(default=False, verbose_name='Estoque já baixado')),
                ('situation', models.CharField(choices=[('ATENDIMENTO', 'Em Atendimento'), ('AGUAR_SEPARACAO', 'Aguardando Separação'), ('SEPARADA', 'Separada'), ('EXPEDICAO', 'Em Expedicação'), ('RECEBIDA', 'Recebida'), ('CANCELADA', 'Cancelada'), ('RASCUNHO', 'Rascunho')], max_length=25, verbose_name='Situação')),
                ('ua_order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='solicitantesconsumo', to='dempam.infoua', verbose_name='Solicitante')),
                ('user_responsible', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='usuario_sol_consumo', to=settings.AUTH_USER_MODEL, verbose_name='Usuário Responsável')),
            ],
            options={
                'verbose_name': 'Solicitações',
                'verbose_name_plural': '09 - Solicitações',
            },
        ),
        migrations.CreateModel(
            name='SolicitacaoItens',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount_order', models.PositiveIntegerField(blank=True, null=True, verbose_name='Quantidade')),
                ('item_order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='itens_solicitados', to='dimms.estoque', verbose_name='Item Solicitado')),
                ('request_defendant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='bens_solicitados', to='dimms.solicitacao', verbose_name='Bens Solicitados')),
            ],
            options={
                'verbose_name': 'Bem Solicitado',
                'verbose_name_plural': '10 - Bens Solicitados',
            },
        ),
        migrations.CreateModel(
            name='SolicitacoesSaldoAtivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(blank=True, editable=False, max_length=30, null=True, unique=True, verbose_name='Código da Solicitação')),
                ('status', models.CharField(choices=[('RASCUNHO', 'Rascunho'), ('ATENDIDA', 'Atendida'), ('CANCELADA', 'Cancelada'), ('EM ANÁLISE', 'Em análise')], default='RASCUNHO', max_length=20, verbose_name='Status')),
                ('data_hora', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Data e Hora da Movimentação')),
                ('contrato', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='contrato_soli_saldoativo', to='dimms.contrato', verbose_name='Contrato')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='usuario_solic_saldoativo', to=settings.AUTH_USER_MODEL, verbose_name='Usuário Responsável')),
            ],
            options={
                'verbose_name': 'Solicitação Saldo Ativo',
                'verbose_name_plural': '05 - Solicitações Saldo Ativo',
            },
        ),
        migrations.AddField(
            model_name='itenssolicitados',
            name='solicitacao',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bensenviados_saldoativo', to='dimms.solicitacoessaldoativo', verbose_name='Solicitação'),
        ),
        migrations.AddField(
            model_name='contrato',
            name='supplier_contract',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='dimms.supplier'),
        ),
        migrations.CreateModel(
            name='Tramitacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('update', models.CharField(blank=True, choices=[('ATENDIMENTO', 'Em Atendimento'), ('AGUAR_SEPARACAO', 'Aguardando Separação'), ('SEPARADA', 'Separada'), ('EXPEDICAO', 'Em Expedicação'), ('RECEBIDA', 'Recebida'), ('CANCELADA', 'Cancelada'), ('RASCUNHO', 'Rascunho')], default='ATENDIMENTO', max_length=30, null=True, verbose_name='Status')),
                ('responsible_update', models.CharField(blank=True, max_length=40, null=True, verbose_name='Responsável pela Atualização')),
                ('observation_update', models.TextField(blank=True, null=True, verbose_name='Observação')),
                ('documents_update', models.FileField(blank=True, null=True, upload_to=dimms.utils.path_solicitation_update, verbose_name='Documento Anexado')),
                ('photo_update', models.ImageField(blank=True, null=True, upload_to=dimms.utils.path_solicitation_photo, verbose_name='Foto do Item')),
                ('date_update', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Data e Hora da Atualização')),
                ('request_update', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='tramitacao', to='dimms.solicitacao', verbose_name='Tramitação')),
                ('user_update', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='usuario_atualizacao', to=settings.AUTH_USER_MODEL, verbose_name='Usuário Responsável')),
            ],
            options={
                'verbose_name': 'Tramitação',
                'verbose_name_plural': '11 - Tramitação',
            },
        ),
        migrations.AddConstraint(
            model_name='itenssolicitados',
            constraint=models.UniqueConstraint(fields=('solicitacao', 'bem'), name='uniq_item_por_solicitacao'),
        ),
    ]
