# Generated by Django 6.0.2 on 2026-02-23 18:45

import dimms.utils
import django.core.validators
import django.db.models.deletion
import localflavor.br.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('dempam', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BensConsumo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('efisco', models.CharField(blank=True, default='Não Consta', max_length=20, verbose_name='E-Fisco')),
                ('descricao_efisco', models.TextField(blank=True, null=True, verbose_name='Descrição Efisco')),
                ('medida', models.CharField(blank=True, choices=[('METRO', 'Metro'), ('UNIDADE', 'Unidade'), ('QUILOGRAMA', 'Quilograma'), ('LITRO', 'Litro'), ('PACOTE', 'Pacote'), ('CAIXA', 'Caixa')], max_length=20, null=True, verbose_name='Unidade de Medida')),
                ('grupo_consumo', models.CharField(blank=True, choices=[('ALIMENTO', 'Alimento'), ('CONFECCAO', 'Confecção'), ('COPA_COZINHA', 'Copa / Cozinha'), ('DOMISSANITARIO', 'Domissanitário'), ('ELETRICA', 'Elétrica'), ('EPI', 'EPI'), ('HIDROSANITARIO', 'Hidrossanitário'), ('INFORMATICA', 'Informática'), ('LIMPEZA', 'Limpeza'), ('MANUTENCAO', 'Manutenção'), ('MARCENARIA', 'Marcenaria'), ('PINTURA', 'Pintura'), ('PAPEIS_EXPEDIENTE', 'Papéis de Expediente'), ('PAPEIS_LIMPEZA', 'Papéis de Limpeza'), ('REFRIGERACAO', 'Refrigeração'), ('TONER', 'Toner')], null=True, verbose_name='Grupo')),
            ],
            options={
                'verbose_name': 'Bem de Consumo',
                'verbose_name_plural': 'Bens de Consumo',
            },
        ),
        migrations.CreateModel(
            name='BensEnviados',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('quantidade', models.PositiveIntegerField(blank=True, null=True, verbose_name='Quantidade Solicitada')),
            ],
        ),
        migrations.CreateModel(
            name='Fornecedor',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('fornecedor', models.CharField(max_length=40, verbose_name='Fornecedor')),
                ('cnpj_fornecedor', localflavor.br.models.BRCNPJField(blank=True, max_length=18, null=True, verbose_name='CNPJ do Fornecedor')),
                ('contato_fornecedor', models.CharField(blank=True, max_length=15, null=True, validators=[django.core.validators.RegexValidator(regex='^\\+?\\d{10,15}$')], verbose_name='Contato do Fornecedor')),
                ('email_fornecedor', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email do Fornecedor')),
            ],
            options={
                'verbose_name': 'Fornecedor',
                'verbose_name_plural': 'Fonecedores',
            },
        ),
        migrations.CreateModel(
            name='Tramitacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='BensConsumoEstoque',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('quantidade', models.PositiveIntegerField(verbose_name='Quantidade')),
                ('local_armazenamento', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='localizacao_consumo', to='dempam.localizacaodempam', verbose_name='Localização')),
                ('solicitacao', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='estoquesolicitacao', to='dimms.bensenviados', verbose_name='Estoque da Solicitação')),
            ],
            options={
                'verbose_name': 'Bem de Consumo',
                'verbose_name_plural': 'Bens de Consumo',
            },
        ),
        migrations.CreateModel(
            name='CompraIndividual',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bem', models.CharField(blank=True, max_length=50, null=True, verbose_name='Bem')),
                ('quantidade', models.PositiveIntegerField(blank=True, null=True, verbose_name='Quantidade')),
                ('valor', models.PositiveIntegerField(verbose_name='Valor')),
                ('nf', models.FileField(blank=True, null=True, upload_to=dimms.utils.caminho_nf_compraindividual, verbose_name='Nota Fiscal')),
                ('data_compra', models.DateField(blank=True, null=True, verbose_name='Data da Compra')),
                ('efisco', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='compras_individuais', to='dimms.bensconsumo', verbose_name='Efisco')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='usuario_compraindividual', to=settings.AUTH_USER_MODEL, verbose_name='Usuário Responsável')),
            ],
        ),
        migrations.CreateModel(
            name='Contrato',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('contrato', models.CharField(max_length=30, verbose_name='N° Contrato')),
                ('inicio_vigencia', models.DateField(blank=True, null=True, verbose_name='Início da Vigência')),
                ('final_vigencia', models.DateField(blank=True, null=True, verbose_name='Final da Vigência')),
                ('homologacao', models.DateField(blank=True, null=True, verbose_name='Homologação')),
                ('cs', models.IntegerField(blank=True, null=True, verbose_name='N° CS')),
                ('cod_liquidacao', models.IntegerField(blank=True, null=True, verbose_name='Código de Licitação')),
                ('fornecedor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='dimms.fornecedor')),
            ],
            options={
                'verbose_name': 'Contrato',
                'verbose_name_plural': 'Contratos',
            },
        ),
        migrations.CreateModel(
            name='SaldoAtivo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('marca', models.CharField(blank=True, max_length=60, null=True, verbose_name='Marca')),
                ('descricao_manual', models.CharField(blank=True, max_length=60, null=True, verbose_name='Descrição Manual')),
                ('quantidade_contrato', models.PositiveIntegerField(verbose_name='Quantidade Contrato')),
                ('saldo_disponivel', models.PositiveIntegerField(blank=True, null=True, verbose_name='Saldo Disponível')),
                ('cota', models.CharField(blank=True, choices=[('PRINCIPAL', 'Principal'), ('RESERVADA', 'Reservada')], max_length=15, null=True, verbose_name='Cota')),
                ('contrato_saldo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='Contrato', to='dimms.contrato', verbose_name='Contrato')),
                ('efisco', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='saldos_ativos', to='dimms.bensconsumo', verbose_name='Efisco')),
            ],
            options={
                'verbose_name': 'Saldo Ativo',
                'verbose_name_plural': 'Saldo Ativo',
                'unique_together': {('contrato_saldo', 'efisco')},
            },
        ),
        migrations.AddField(
            model_name='bensenviados',
            name='bem',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='itens_enviados', to='dimms.saldoativo', verbose_name='Item do Contrato (Saldo Ativo)'),
        ),
        migrations.CreateModel(
            name='SolicitacoesConsumo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('quantidade', models.PositiveIntegerField(verbose_name='Quantidade')),
                ('data_hora', models.DateTimeField(auto_now_add=True, verbose_name='Data e Hora da Movimentação')),
                ('observacao', models.TextField(blank=True, null=True, verbose_name='Observação')),
                ('anexo', models.FileField(blank=True, null=True, upload_to=dimms.utils.caminho_movimentacao_consumo, verbose_name='Documento Anexado')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='itens_movimentados', to='dimms.bensconsumo', verbose_name='Item Movimentado')),
                ('solicitante', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='solicitantesconsumo', to='dempam.infoua', verbose_name='Solicitante')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='usuario_sol_consumo', to=settings.AUTH_USER_MODEL, verbose_name='Usuário Responsável')),
            ],
            options={
                'verbose_name': 'Movimentação (Consumo)',
                'verbose_name_plural': 'Movimentações (Consumo)',
            },
        ),
        migrations.CreateModel(
            name='SolicitacoesSaldoAtivo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('codigo', models.CharField(editable=False, max_length=30, unique=True, verbose_name='Código da Solicitação')),
                ('status', models.CharField(choices=[('ABERTO', 'Aberto'), ('FECHADO', 'Fechado')], default='Rascunho', max_length=20, verbose_name='Status')),
                ('data_hora', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Data e Hora da Movimentação')),
                ('contrato', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='contrato_soli_saldoativo', to='dimms.contrato', verbose_name='Contrato')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='usuario_solic_saldoativo', to=settings.AUTH_USER_MODEL, verbose_name='Usuário Responsável')),
            ],
            options={
                'verbose_name': 'Solicitação Saldo Ativo',
                'verbose_name_plural': 'Solicitação Saldo Ativo',
            },
        ),
        migrations.AddField(
            model_name='bensenviados',
            name='solicitacao',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bensenviados_saldoativo', to='dimms.solicitacoessaldoativo', verbose_name='Solicitação'),
        ),
        migrations.AddConstraint(
            model_name='bensenviados',
            constraint=models.UniqueConstraint(fields=('solicitacao', 'bem'), name='uniq_item_por_solicitacao'),
        ),
    ]
