# Generated by Django 6.0.2 on 2026-02-23 20:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dimms', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='BensEnviados',
            new_name='ItensSolicitados',
        ),
        migrations.AlterModelOptions(
            name='bensconsumo',
            options={'verbose_name': 'Bem de Consumo', 'verbose_name_plural': '01 - Bens de Consumo'},
        ),
        migrations.AlterModelOptions(
            name='contrato',
            options={'verbose_name': 'Contrato', 'verbose_name_plural': '03 - Contratos'},
        ),
        migrations.AlterModelOptions(
            name='fornecedor',
            options={'verbose_name': 'Fornecedor', 'verbose_name_plural': '02 - Fonecedores'},
        ),
        migrations.AlterModelOptions(
            name='itenssolicitados',
            options={'verbose_name': 'Item Solicitado', 'verbose_name_plural': '06 - Itens Solicitados'},
        ),
        migrations.AlterModelOptions(
            name='saldoativo',
            options={'verbose_name': 'Saldo Ativo', 'verbose_name_plural': '04 - Saldo Ativo'},
        ),
        migrations.AlterModelOptions(
            name='solicitacoessaldoativo',
            options={'verbose_name': 'Solicitação Saldo Ativo', 'verbose_name_plural': '05 - Solicitações Saldo Ativo'},
        ),
    ]
