# Generated by Django 6.0.2 on 2026-03-31 16:14

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dimms', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='estoque',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Data de Cadastro'),
            preserve_default=False,
        ),
    ]
