# Generated by Django 6.0.2 on 2026-05-12 17:10

import dimms.utils
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dempam', '0001_initial'),
        ('dimms', '0002_estoque_created_at'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='artifacts',
            options={'verbose_name': 'Artefato', 'verbose_name_plural': '12 - Artefatos'},
        ),
        migrations.AlterModelOptions(
            name='itensartifacts',
            options={'verbose_name': 'Item Artefato', 'verbose_name_plural': '13 - Itens Artefatos'},
        ),
        migrations.AlterModelOptions(
            name='itensproposal',
            options={'verbose_name': 'Item Proposta', 'verbose_name_plural': '15 - Itens Propostas'},
        ),
        migrations.AlterModelOptions(
            name='proposal',
            options={'verbose_name': 'Proposta', 'verbose_name_plural': '14 - Propostas'},
        ),
        migrations.CreateModel(
            name='CatalogoConsumo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=200, verbose_name='Descrição')),
                ('mark', models.CharField(blank=True, max_length=80, verbose_name='Marca')),
                ('detalhes', models.TextField(blank=True, verbose_name='Detalhes')),
                ('medida', models.CharField(choices=[('METRO', 'Metro'), ('UNIDADE', 'Unidade'), ('QUILOGRAMA', 'Quilograma'), ('LITRO', 'Litro'), ('PACOTE', 'Pacote'), ('CAIXA', 'Caixa')], default='UNIDADE', max_length=20, verbose_name='Unidade de Medida')),
                ('grupo_consumo', models.CharField(choices=[('ALIMENTO', 'Alimento'), ('CONFECCAO', 'Confecção'), ('COPA_COZINHA', 'Copa / Cozinha'), ('DOMISSANITARIO', 'Domissanitário'), ('ELETRICA', 'Elétrica'), ('EPI', 'EPI'), ('HIDROSANITARIO', 'Hidrossanitário'), ('INFORMATICA', 'Informática'), ('LIMPEZA', 'Limpeza'), ('MANUTENCAO', 'Manutenção'), ('MARCENARIA', 'Marcenaria'), ('PINTURA', 'Pintura'), ('PAPEIS_EXPEDIENTE', 'Papéis de Expediente'), ('PAPEIS_LIMPEZA', 'Papéis de Limpeza'), ('REFRIGERACAO', 'Refrigeração'), ('TONER', 'Toner')], default='PAPEIS_EXPEDIENTE', max_length=50, verbose_name='Grupo')),
                ('photo', models.ImageField(blank=True, null=True, upload_to=dimms.utils.path_photo_catalogo_consumo, verbose_name='Foto')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo no catálogo')),
                ('efisco', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='catalogo_consumo', to='dimms.bensconsumo', verbose_name='E-Fisco')),
            ],
            options={
                'verbose_name': 'Catálogo Consumo',
                'verbose_name_plural': 'Catálogo de Consumo',
                'ordering': ['grupo_consumo', 'description'],
            },
        ),
        migrations.CreateModel(
            name='SolicitacaoCatalogoConsumo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(blank=True, editable=False, max_length=30, unique=True, verbose_name='Código')),
                ('status', models.CharField(choices=[('PENDENTE', 'Pendente'), ('ATENDIDA', 'Atendida'), ('REJEITADA', 'Rejeitada'), ('CANCELADA', 'Cancelada')], default='PENDENTE', max_length=20, verbose_name='Status')),
                ('data', models.DateTimeField(auto_now_add=True, verbose_name='Data')),
                ('observacao', models.TextField(blank=True, verbose_name='Observação')),
                ('obs_decisao', models.TextField(blank=True, verbose_name='Observação da Decisão')),
                ('data_decisao', models.DateTimeField(blank=True, null=True, verbose_name='Data da Decisão')),
                ('decidido_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='decisoes_catalogo_consumo', to=settings.AUTH_USER_MODEL, verbose_name='Decidido por')),
                ('solicitante', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='solicitacoes_catalogo_consumo', to=settings.AUTH_USER_MODEL, verbose_name='Solicitante')),
                ('ua_destino', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='solicitacoes_catalogo_consumo', to='dempam.infoua', verbose_name='UA Destino')),
            ],
            options={
                'verbose_name': 'Solicitação Catálogo Consumo',
                'verbose_name_plural': 'Solicitações Catálogo Consumo',
                'ordering': ['-data'],
            },
        ),
        migrations.CreateModel(
            name='ItemSolicitacaoCatalogoConsumo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.PositiveIntegerField(default=1, verbose_name='Quantidade')),
                ('observacao', models.TextField(blank=True, verbose_name='Observação')),
                ('catalogo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='itens_solicitados', to='dimms.catalogoconsumo', verbose_name='Item do Catálogo')),
                ('solicitacao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens', to='dimms.solicitacaocatalogoconsumo', verbose_name='Solicitação')),
            ],
            options={
                'verbose_name': 'Item Solicitação Catálogo Consumo',
                'verbose_name_plural': 'Itens Solicitação Catálogo Consumo',
            },
        ),
    ]
