# Generated by Django 6.0.2 on 2026-02-23 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dimms', '0002_rename_bensenviados_itenssolicitados_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BensEnviados',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AlterField(
            model_name='solicitacoessaldoativo',
            name='status',
            field=models.CharField(choices=[('RASCUNHO', 'Rascunho'), ('ATENDIDA', 'Atendida'), ('CANCELADA', 'Cancelada'), ('EM ANÁLISE', 'Em análise')], default='RASCUNHO', max_length=20, verbose_name='Status'),
        ),
    ]
