# Generated by Django 6.0.2 on 2026-06-11 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dimms', '0003_alter_artifacts_options_alter_itensartifacts_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bensconsumo',
            name='almoxarifado',
            field=models.CharField(choices=[('GERAL', 'Almoxarifado Geral'), ('RESERVADO', 'Almoxarifado Reservado')], default='GERAL', max_length=20, verbose_name='Almoxarifado'),
        ),
    ]
