# Generated by Django 6.0.2 on 2026-02-24 17:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dimms', '0003_bensenviados_alter_solicitacoessaldoativo_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bensenviados',
            options={'verbose_name': 'Item Enviado', 'verbose_name_plural': '07 - Itens Enviados'},
        ),
        migrations.AddField(
            model_name='bensenviados',
            name='data_envio',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Data/Hora do Envio'),
        ),
        migrations.AddField(
            model_name='bensenviados',
            name='item_enviado',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='itemenviado', to='dimms.itenssolicitados', verbose_name='Itens Enviados'),
        ),
        migrations.AddField(
            model_name='bensenviados',
            name='quantidade_enviada',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Quantidade Enviada'),
        ),
        migrations.AlterField(
            model_name='bensenviados',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
