# Generated by Django 6.0.2 on 2026-06-12 17:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dimms', '0004_bensconsumo_almoxarifado'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bensenviados',
            options={'verbose_name': 'Remessa', 'verbose_name_plural': '07 - Remessas'},
        ),
        migrations.AddField(
            model_name='bensenviados',
            name='data_recebimento',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Data/Hora do Recebimento'),
        ),
        migrations.AddField(
            model_name='bensenviados',
            name='observacao',
            field=models.CharField(blank=True, max_length=300, verbose_name='Observação'),
        ),
        migrations.AddField(
            model_name='bensenviados',
            name='recebida',
            field=models.BooleanField(default=False, verbose_name='Recebida'),
        ),
        migrations.AlterField(
            model_name='bensenviados',
            name='data_envio',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Data/Hora do Registro da Remessa'),
        ),
        migrations.AlterField(
            model_name='bensenviados',
            name='item_enviado',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='remessas', to='dimms.itenssolicitados', verbose_name='Item Solicitado'),
        ),
        migrations.AlterField(
            model_name='bensenviados',
            name='quantidade_enviada',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Quantidade Enviada pelo Fornecedor'),
        ),
    ]
