# Generated by Django 6.0.2 on 2026-03-02 14:12

import dimms.utils
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dempam', '0003_alter_circunscricaopredio_id_alter_infoua_id_and_more'),
        ('dimms', '0004_alter_bensenviados_options_bensenviados_data_envio_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='solicitacoesconsumo',
            name='item',
        ),
        migrations.RemoveField(
            model_name='solicitacoesconsumo',
            name='solicitante',
        ),
        migrations.RemoveField(
            model_name='solicitacoesconsumo',
            name='usuario',
        ),
        migrations.AlterModelOptions(
            name='tramitacao',
            options={'verbose_name': 'Tramitação', 'verbose_name_plural': 'Tramitação'},
        ),
        migrations.AddField(
            model_name='tramitacao',
            name='date_update',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Data e Hora da Atualização'),
        ),
        migrations.AddField(
            model_name='tramitacao',
            name='documents_update',
            field=models.FileField(blank=True, null=True, upload_to=dimms.utils.caminho_consum_update, verbose_name='Documento Anexado'),
        ),
        migrations.AddField(
            model_name='tramitacao',
            name='observation_update',
            field=models.TextField(blank=True, null=True, verbose_name='Observação'),
        ),
        migrations.AddField(
            model_name='tramitacao',
            name='update',
            field=models.CharField(blank=True, choices=[('PROCESSAMENTO', 'EM Processamento'), ('SEPARADA', 'Separada'), ('ENVIO', 'Para Envio'), ('TRAMITACAO', 'Em Tramitação'), ('RECEBIDA', 'Recebida'), ('CANCELADA', 'Cancelada')], max_length=30, null=True, verbose_name='Status'),
        ),
        migrations.AddField(
            model_name='tramitacao',
            name='user_update',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='usuario_atualizacao', to=settings.AUTH_USER_MODEL, verbose_name='Usuário Responsável'),
        ),
        migrations.AlterField(
            model_name='bensconsumo',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='bensenviados',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='contrato',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='fornecedor',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='itenssolicitados',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='saldoativo',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='solicitacoessaldoativo',
            name='codigo',
            field=models.CharField(blank=True, editable=False, max_length=30, null=True, unique=True, verbose_name='Código da Solicitação'),
        ),
        migrations.AlterField(
            model_name='solicitacoessaldoativo',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.CreateModel(
            name='Estoque',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description_manual', models.CharField(max_length=90, verbose_name='Descrição Manual')),
                ('mark', models.CharField(max_length=40, verbose_name='Marca')),
                ('amount_shock', models.PositiveIntegerField(verbose_name='Quantidade')),
                ('item_shock', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bem_estoque', to='dimms.bensconsumo', verbose_name='Bem no Estoque')),
                ('locate', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='localizacao_consumo', to='dempam.localizacaodempam', verbose_name='Localização')),
            ],
            options={
                'verbose_name': 'Bem em Estoque',
                'verbose_name_plural': 'Bens em Estoque',
            },
        ),
        migrations.CreateModel(
            name='Solicitacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request', models.CharField(editable=False, max_length=30, unique=True, verbose_name='Código da Solicitação')),
                ('data_order', models.DateTimeField(auto_now_add=True, verbose_name='Data e Hora da Movimentação')),
                ('observation_order', models.TextField(blank=True, null=True, verbose_name='Observação')),
                ('documents_order', models.FileField(blank=True, null=True, upload_to=dimms.utils.caminho_movimentacao_consumo, verbose_name='Documento Anexado')),
                ('situation', models.CharField(max_length=20, verbose_name='Situação')),
                ('user_order', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='solicitantesconsumo', to='dempam.infoua', verbose_name='Solicitante')),
                ('user_responsible', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='usuario_sol_consumo', to=settings.AUTH_USER_MODEL, verbose_name='Usuário Responsável')),
            ],
            options={
                'verbose_name': 'Movimentação (Consumo)',
                'verbose_name_plural': 'Movimentações (Consumo)',
            },
        ),
        migrations.AddField(
            model_name='tramitacao',
            name='request_update',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='tramitacao', to='dimms.solicitacao', verbose_name='Tramitação'),
        ),
        migrations.CreateModel(
            name='SolicitacaoItens',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amont_order', models.PositiveIntegerField(blank=True, null=True, verbose_name='Quantidade')),
                ('item_order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='itens_solicitados', to='dimms.bensconsumo', verbose_name='Item Solicitado')),
                ('request_defendant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='itens_solicitados', to='dimms.solicitacao', verbose_name='Itens Solicitados')),
            ],
            options={
                'verbose_name': 'Item Solicitado',
                'verbose_name_plural': 'Itens Solicitados',
            },
        ),
        migrations.DeleteModel(
            name='BensConsumoEstoque',
        ),
        migrations.DeleteModel(
            name='SolicitacoesConsumo',
        ),
    ]
