# Generated by Django 6.0.2 on 2026-03-03 11:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dimms', '0005_remove_solicitacoesconsumo_item_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bensenviados',
            options={'verbose_name': 'Item Enviado', 'verbose_name_plural': '07 - Bens Enviados'},
        ),
        migrations.AlterModelOptions(
            name='estoque',
            options={'verbose_name': 'Bem Estoque', 'verbose_name_plural': '08 - Bens Estoque'},
        ),
        migrations.AlterModelOptions(
            name='itenssolicitados',
            options={'verbose_name': 'Bens Solicitado', 'verbose_name_plural': '06 - Bens Solicitados'},
        ),
        migrations.AlterModelOptions(
            name='solicitacao',
            options={'verbose_name': 'Solicitações', 'verbose_name_plural': '09 - Solicitações'},
        ),
        migrations.AlterModelOptions(
            name='solicitacaoitens',
            options={'verbose_name': 'Bem Solicitado', 'verbose_name_plural': '10 - Bens Solicitados'},
        ),
        migrations.AlterModelOptions(
            name='tramitacao',
            options={'verbose_name': 'Tramitação', 'verbose_name_plural': '11 - Tramitação'},
        ),
        migrations.AlterField(
            model_name='bensenviados',
            name='item_enviado',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='itemenviado', to='dimms.itenssolicitados', verbose_name='Bens Enviados'),
        ),
        migrations.AlterField(
            model_name='solicitacao',
            name='situation',
            field=models.CharField(choices=[('PROCESSAMENTO', 'EM Processamento'), ('SEPARADA', 'Separada'), ('ENVIO', 'Para Envio'), ('TRAMITACAO', 'Em Tramitação'), ('RECEBIDA', 'Recebida'), ('CANCELADA', 'Cancelada')], max_length=25, verbose_name='Situação'),
        ),
        migrations.AlterField(
            model_name='solicitacaoitens',
            name='request_defendant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='bens_solicitados', to='dimms.solicitacao', verbose_name='Bens Solicitados'),
        ),
    ]
