# Generated by Django 6.0.2 on 2026-06-15 14:42

import dimms.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dimms', '0005_alter_bensenviados_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bensenviados',
            name='comprovante',
            field=models.FileField(blank=True, help_text='Nota fiscal, termo de recebimento ou outro documento (PDF, imagem)', null=True, upload_to=dimms.utils.path_comprovante_remessa, verbose_name='Comprovante de Recebimento'),
        ),
    ]
