# Generated by Django 6.0.2 on 2026-03-03 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dimms', '0006_alter_bensenviados_options_alter_estoque_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='estoque',
            name='validity',
            field=models.DateField(blank=True, null=True, verbose_name='Validade'),
        ),
    ]
