# Generated by Django 6.0.2 on 2026-07-01 14:57

from django.db import migrations, models


def fix_null_supplier_fields(apps, schema_editor):
    Supplier = apps.get_model('dimms', 'Supplier')
    Supplier.objects.filter(cnpj_supplier__isnull=True).update(cnpj_supplier='')
    Supplier.objects.filter(name_responsible__isnull=True).update(name_responsible='')
    Supplier.objects.filter(cpf_responsible__isnull=True).update(cpf_responsible='')
    Supplier.objects.filter(contact_supplier__isnull=True).update(contact_supplier='')
    Supplier.objects.filter(email_supplier__isnull=True).update(email_supplier='')


class Migration(migrations.Migration):

    dependencies = [
        ('dimms', '0006_bensrenviados_comprovante'),
    ]

    operations = [
        migrations.RunPython(fix_null_supplier_fields, migrations.RunPython.noop),
        migrations.AddField(
            model_name='contrato',
            name='aditivo_prazo',
            field=models.CharField(blank=True, max_length=100, verbose_name='Aditivo de Prazo'),
        ),
        migrations.AddField(
            model_name='contrato',
            name='aditivo_preco',
            field=models.CharField(blank=True, max_length=100, verbose_name='Aditivo de Preço'),
        ),
        migrations.AddField(
            model_name='contrato',
            name='categoria',
            field=models.CharField(blank=True, max_length=60, verbose_name='Categoria'),
        ),
        migrations.AddField(
            model_name='contrato',
            name='forma',
            field=models.CharField(blank=True, choices=[('ATA', 'ATA'), ('PARC', 'PARC'), ('CD', 'CD')], max_length=10, verbose_name='Forma'),
        ),
        migrations.AddField(
            model_name='contrato',
            name='numero_arp',
            field=models.CharField(blank=True, max_length=60, verbose_name='N° ARP PE Integrado'),
        ),
        migrations.AddField(
            model_name='contrato',
            name='numero_contrato_oficial',
            field=models.CharField(blank=True, max_length=30, verbose_name='N° Contrato Oficial'),
        ),
        migrations.AddField(
            model_name='contrato',
            name='numero_processo',
            field=models.CharField(blank=True, max_length=60, verbose_name='N° Processo Eletrônico'),
        ),
        migrations.AddField(
            model_name='contrato',
            name='numero_sc',
            field=models.CharField(blank=True, max_length=30, verbose_name='N° SC'),
        ),
        migrations.AddField(
            model_name='contrato',
            name='previsao_anual',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True, verbose_name='Previsão Anual (R$)'),
        ),
        migrations.AddField(
            model_name='contrato',
            name='valor_contratado',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True, verbose_name='Valor Contratado (R$)'),
        ),
        migrations.AddField(
            model_name='saldoativo',
            name='numero_item',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='N° Item no Contrato'),
        ),
        migrations.AddField(
            model_name='saldoativo',
            name='preco_unitario',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True, verbose_name='Preço Unitário (R$)'),
        ),
        migrations.AlterField(
            model_name='contrato',
            name='contrato',
            field=models.CharField(max_length=60, verbose_name='N° Contrato (MPPE)'),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='supplier',
            field=models.CharField(max_length=100, verbose_name='Fornecedor'),
        ),
    ]
