# Generated by Django 6.0.2 on 2026-03-03 14:03

import dimms.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dimms', '0007_estoque_validity'),
    ]

    operations = [
        migrations.AddField(
            model_name='estoque',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to=dimms.utils.caminho_bensconsumo, verbose_name='Foto do Item'),
        ),
    ]
