# Generated by Django 6.0.2 on 2026-07-08 15:28

import dimms.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dimms', '0007_contrato_aditivo_prazo_contrato_aditivo_preco_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitacoessaldoativo',
            name='nota_fiscal',
            field=models.FileField(blank=True, null=True, upload_to=dimms.utils.path_nota_fiscal_solicitacao, verbose_name='Nota Fiscal (PDF)'),
        ),
        migrations.AddField(
            model_name='solicitacoessaldoativo',
            name='numero_empenho',
            field=models.CharField(blank=True, max_length=50, verbose_name='N° Empenho'),
        ),
        migrations.AddField(
            model_name='solicitacoessaldoativo',
            name='numero_sei',
            field=models.CharField(blank=True, max_length=50, verbose_name='N° SEI'),
        ),
    ]
