# Generated by Django 6.0.2 on 2026-07-02 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dimms', '0007_contrato_aditivo_prazo_contrato_aditivo_preco_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contrato',
            name='cod_liquidacao',
            field=models.BigIntegerField(blank=True, null=True, verbose_name='Código de Licitação'),
        ),
    ]
