# Generated by Django 6.0.2 on 2026-03-05 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dimms', '0008_estoque_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='estoque',
            name='essential',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='Essencial'),
        ),
        migrations.AddField(
            model_name='estoque',
            name='monthly_consumption',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Consumo Mensal'),
        ),
    ]
