# Generated by Django 6.0.2 on 2026-03-05 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dimms', '0009_estoque_essential_estoque_monthly_consumption'),
    ]

    operations = [
        migrations.AddField(
            model_name='estoque',
            name='duration',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Duração (Meses)'),
        ),
    ]
