# Generated by Django 6.0.2 on 2026-07-13 17:14

from django.db import migrations, models


def backfill_status(apps, schema_editor):
    Contrato = apps.get_model('dimms', 'Contrato')
    Contrato.objects.filter(status__isnull=True).update(status='VIGENTE')


class Migration(migrations.Migration):

    dependencies = [
        ('dimms', '0010_add_numero_nota_fiscal'),
    ]

    operations = [
        migrations.RunPython(backfill_status, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='contrato',
            name='status',
            field=models.CharField(choices=[('VIGENTE', 'Vigente'), ('CANCELADO', 'Cancelado')], default='VIGENTE', max_length=20, verbose_name='Status do Contrato'),
        ),
    ]
