# Generated by Django 6.0.2 on 2026-03-09 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dimms', '0010_estoque_duration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estoque',
            name='duration',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Duração (Meses)'),
        ),
    ]
