# Generated by Django 6.0.2 on 2026-03-09 11:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dimms', '0011_alter_estoque_duration'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='estoque',
            name='duration',
        ),
    ]
