# Generated by Django 6.0.2 on 2026-07-17 16:22

import dimms.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dimms', '0011_alter_contrato_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitacoessaldoativo',
            name='empenho',
            field=models.FileField(blank=True, null=True, upload_to=dimms.utils.path_empenho_solicitacao, verbose_name='Empenho (PDF)'),
        ),
        migrations.AddField(
            model_name='solicitacoessaldoativo',
            name='termo_recebimento_definitivo',
            field=models.FileField(blank=True, null=True, upload_to=dimms.utils.path_termo_recebimento_solicitacao, verbose_name='Termo de Recebimento Definitivo (PDF)'),
        ),
    ]
