# Generated by Django 6.0.2 on 2026-07-20 14:38

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dimms', '0012_solicitacoessaldoativo_empenho_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bensenviados',
            name='quantidade_enviada',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Quantidade Enviada pelo Fornecedor'),
        ),
        migrations.AlterField(
            model_name='estoque',
            name='amount_shock',
            field=models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Quantidade'),
        ),
        migrations.AlterField(
            model_name='itenssolicitados',
            name='quantidade',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Quantidade Solicitada'),
        ),
        migrations.AlterField(
            model_name='saldoativo',
            name='quantidade_contrato',
            field=models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Quantidade Contrato'),
        ),
        migrations.AlterField(
            model_name='saldoativo',
            name='saldo_disponivel',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Saldo Disponível'),
        ),
        migrations.AlterField(
            model_name='solicitacaoitens',
            name='amount_order',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Quantidade'),
        ),
    ]
