# Generated by Django 5.2.16 on 2026-07-22 14:49
# (arquivo revisado manualmente — o makemigrations original incluiu AlterField
#  espúrios no campo "id" de models existentes por causa da versão do Django
#  usada pra gerar o arquivo (5.2) divergir da versão do projeto (6.0.2).
#  Mantidas apenas as operações reais: os 3 models novos de Acompanhamentos SEI.)

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dimms', '0013_alter_bensenviados_quantidade_enviada_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Sei',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sei_number', models.CharField(help_text='Ex.: 19.16.0001234567/2026-00', max_length=50, unique=True, verbose_name='Número do SEI')),
                ('description', models.CharField(blank=True, max_length=255, verbose_name='Assunto/Descrição')),
                ('status', models.CharField(choices=[('EM_ANDAMENTO', 'Em Andamento'), ('CONCLUIDO', 'Concluído'), ('ARQUIVADO', 'Arquivado')], default='EM_ANDAMENTO', max_length=20, verbose_name='Status')),
                ('date', models.DateField(default=django.utils.timezone.localdate, verbose_name='Data de Abertura')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última modificação')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='seis_acompanhados', to=settings.AUTH_USER_MODEL, verbose_name='Responsável')),
            ],
            options={
                'verbose_name': 'Acompanhamento SEI',
                'verbose_name_plural': '17 - Acompanhamentos SEI',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='SeiUpdate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='Atualização')),
                ('date', models.DateField(default=django.utils.timezone.localdate, verbose_name='Data da Atualização')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('sei', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='updates', to='dimms.sei', verbose_name='Acompanhamento SEI')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='atualizacoes_sei', to=settings.AUTH_USER_MODEL, verbose_name='Registrado por')),
            ],
            options={
                'verbose_name': 'Atualização SEI',
                'verbose_name_plural': '18 - Atualizações SEI',
                'ordering': ['-date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Nome do Tema')),
                ('color', models.CharField(default='#2563EB', help_text='Cor em hexadecimal (ex.: #2563EB)', max_length=7, verbose_name='Cor')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='temas_criados', to=settings.AUTH_USER_MODEL, verbose_name='Criado por')),
            ],
            options={
                'verbose_name': 'Tema',
                'verbose_name_plural': '16 - Temas (Acompanhamentos)',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='sei',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='seis', to='dimms.subject', verbose_name='Tema'),
        ),
    ]
