# Generated by Django 6.0.2 on 2026-03-09 15:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dempam', '0003_alter_circunscricaopredio_id_alter_infoua_id_and_more'),
        ('dimms', '0013_alter_estoque_options_estoque_duration'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='estoque',
            options={'verbose_name': 'Bem Estoque', 'verbose_name_plural': '08 - Bens Estoque'},
        ),
        migrations.RenameField(
            model_name='solicitacao',
            old_name='request',
            new_name='request_code',
        ),
        migrations.RemoveField(
            model_name='estoque',
            name='duration',
        ),
        migrations.AddField(
            model_name='solicitacao',
            name='ua_order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='solicitantesconsumo', to='dempam.infoua', verbose_name='Solicitante'),
        ),
        migrations.AlterField(
            model_name='solicitacao',
            name='user_order',
            field=models.CharField(blank=True, max_length=40, null=True, verbose_name='Usuário Solicitante'),
        ),
    ]
