# Generated by Django 6.0.2 on 2026-03-10 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dimms', '0014_alter_estoque_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='solicitacaoitens',
            old_name='amont_order',
            new_name='amount_order',
        ),
        migrations.AlterField(
            model_name='solicitacao',
            name='situation',
            field=models.CharField(choices=[('PROCESSAMENTO', 'EM Processamento'), ('SEPARADA', 'Separada'), ('TRAMITACAO', 'Em Tramitação'), ('RECEBIDA', 'Recebida'), ('CANCELADA', 'Cancelada')], max_length=25, verbose_name='Situação'),
        ),
        migrations.AlterField(
            model_name='tramitacao',
            name='update',
            field=models.CharField(blank=True, choices=[('PROCESSAMENTO', 'EM Processamento'), ('SEPARADA', 'Separada'), ('TRAMITACAO', 'Em Tramitação'), ('RECEBIDA', 'Recebida'), ('CANCELADA', 'Cancelada')], max_length=30, null=True, verbose_name='Status'),
        ),
    ]
