# Generated by Django 6.0.2 on 2026-03-10 10:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dimms', '0015_rename_amont_order_solicitacaoitens_amount_order_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solicitacaoitens',
            name='item_order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='itens_solicitados', to='dimms.estoque', verbose_name='Item Solicitado'),
        ),
    ]
