# Generated by Django 6.0.2 on 2026-07-29 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dempam', '0006_configuracaopaineltv'),
        ('dimms', '0016_remove_sei_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='estoque',
            name='outras_localizacoes',
            field=models.ManyToManyField(blank=True, related_name='itens_tambem_aqui', to='dempam.localizacaodempam', verbose_name='Outras localizações'),
        ),
    ]
