# Generated by Django 6.0.2 on 2026-03-10 11:55

import dimms.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dimms', '0016_alter_solicitacaoitens_item_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='tramitacao',
            name='photo_update',
            field=models.ImageField(blank=True, null=True, upload_to=dimms.utils.caminho_consum_update, verbose_name='Foto do Item'),
        ),
    ]
