# Generated by Django 6.0.2 on 2026-03-10 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dimms', '0017_tramitacao_photo_update'),
    ]

    operations = [
        migrations.AddField(
            model_name='tramitacao',
            name='responsible_update',
            field=models.CharField(blank=True, max_length=40, null=True, verbose_name='Responsável pela Atualização'),
        ),
    ]
