# Generated by Django 6.0.2 on 2026-07-30 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dimms', '0017_estoque_outras_localizacoes'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitacaoitens',
            name='separado',
            field=models.BooleanField(default=False, verbose_name='Separado'),
        ),
    ]
