# Generated by Django 6.0.2 on 2026-03-11 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dimms', '0018_tramitacao_responsible_update'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solicitacao',
            name='situation',
            field=models.CharField(choices=[('ATENDIMENTO', 'Em Atendimento'), ('AGUAR_SEPARACAO', 'Aguardando Separação'), ('SEPARADA', 'Separada'), ('EXPEDICAO', 'Em Expedicação'), ('RECEBIDA', 'Recebida'), ('CANCELADA', 'Cancelada')], max_length=25, verbose_name='Situação'),
        ),
        migrations.AlterField(
            model_name='tramitacao',
            name='update',
            field=models.CharField(blank=True, choices=[('ATENDIMENTO', 'Em Atendimento'), ('AGUAR_SEPARACAO', 'Aguardando Separação'), ('SEPARADA', 'Separada'), ('EXPEDICAO', 'Em Expedicação'), ('RECEBIDA', 'Recebida'), ('CANCELADA', 'Cancelada')], max_length=30, null=True, verbose_name='Status'),
        ),
    ]
