# Generated by Django 6.0.2 on 2026-07-31 15:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dempam', '0008_configuracaopaineltv_video_arquivo_and_more'),
        ('dimms', '0018_solicitacaoitens_separado'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PeriodoInventarioConsumo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mes', models.PositiveSmallIntegerField(verbose_name='Mês')),
                ('ano', models.PositiveSmallIntegerField(verbose_name='Ano')),
                ('aberto', models.BooleanField(default=True, verbose_name='Aberto')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('encerrado_em', models.DateTimeField(blank=True, null=True, verbose_name='Encerrado em')),
                ('criado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='periodos_inventario_criados', to=settings.AUTH_USER_MODEL, verbose_name='Criado por')),
            ],
            options={
                'verbose_name': 'Período de Inventário',
                'verbose_name_plural': '12 - Períodos de Inventário (Consumo)',
                'ordering': ['-ano', '-mes'],
                'unique_together': {('mes', 'ano')},
            },
        ),
        migrations.CreateModel(
            name='ConferenciaEstoque',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade_anterior', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Quantidade Anterior')),
                ('quantidade_conferida', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Quantidade Conferida')),
                ('observacao', models.CharField(blank=True, max_length=200, verbose_name='Observação')),
                ('conferido_em', models.DateTimeField(auto_now_add=True, verbose_name='Conferido em')),
                ('conferido_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='conferencias_estoque', to=settings.AUTH_USER_MODEL, verbose_name='Conferido por')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conferencias_inventario', to='dimms.estoque', verbose_name='Item')),
                ('localizacao_anterior', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='dempam.localizacaodempam', verbose_name='Localização Anterior')),
                ('localizacao_conferida', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='dempam.localizacaodempam', verbose_name='Localização Conferida')),
                ('periodo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conferencias', to='dimms.periodoinventarioconsumo', verbose_name='Período')),
            ],
            options={
                'verbose_name': 'Conferência de Estoque',
                'verbose_name_plural': '13 - Conferências de Estoque',
                'ordering': ['-conferido_em'],
                'unique_together': {('periodo', 'item')},
            },
        ),
    ]
