# Generated by Django 6.0.2 on 2026-08-03 14:19

import dimms.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dimms', '0019_periodoinventarioconsumo_conferenciaestoque'),
    ]

    operations = [
        migrations.AddField(
            model_name='tramitacao',
            name='assinatura_recebedor',
            field=models.ImageField(blank=True, null=True, upload_to=dimms.utils.path_solicitation_assinatura, verbose_name='Assinatura de Quem Recebeu'),
        ),
    ]
