# Generated by Django 6.0.2 on 2026-03-11 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dimms', '0019_alter_solicitacao_situation_alter_tramitacao_update'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tramitacao',
            name='update',
            field=models.CharField(blank=True, choices=[('ATENDIMENTO', 'Em Atendimento'), ('AGUAR_SEPARACAO', 'Aguardando Separação'), ('SEPARADA', 'Separada'), ('EXPEDICAO', 'Em Expedicação'), ('RECEBIDA', 'Recebida'), ('CANCELADA', 'Cancelada')], default='ATENDIMENTO', max_length=30, null=True, verbose_name='Status'),
        ),
    ]
