# Generated by Django 6.0.2 on 2026-08-03 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dimms', '0020_tramitacao_assinatura_recebedor'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitacao',
            name='numero_pe_integrado',
            field=models.CharField(blank=True, max_length=60, null=True, verbose_name='N° PE Integrado'),
        ),
    ]
