# Generated by Django 6.0.2 on 2026-03-16 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dimms', '0020_alter_tramitacao_update'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='estoque',
            name='monthly_consumption',
        ),
        migrations.AddField(
            model_name='contrato',
            name='status',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Status do Contrato'),
        ),
        migrations.AddField(
            model_name='solicitacao',
            name='stock_deducted',
            field=models.BooleanField(default=False, verbose_name='Estoque já baixado'),
        ),
        migrations.AlterField(
            model_name='solicitacao',
            name='situation',
            field=models.CharField(choices=[('ATENDIMENTO', 'Em Atendimento'), ('AGUAR_SEPARACAO', 'Aguardando Separação'), ('SEPARADA', 'Separada'), ('EXPEDICAO', 'Em Expedicação'), ('RECEBIDA', 'Recebida'), ('CANCELADA', 'Cancelada'), ('RASCUNHO', 'Rascunho')], max_length=25, verbose_name='Situação'),
        ),
        migrations.AlterField(
            model_name='tramitacao',
            name='update',
            field=models.CharField(blank=True, choices=[('ATENDIMENTO', 'Em Atendimento'), ('AGUAR_SEPARACAO', 'Aguardando Separação'), ('SEPARADA', 'Separada'), ('EXPEDICAO', 'Em Expedicação'), ('RECEBIDA', 'Recebida'), ('CANCELADA', 'Cancelada'), ('RASCUNHO', 'Rascunho')], default='ATENDIMENTO', max_length=30, null=True, verbose_name='Status'),
        ),
    ]
