# Generated by Django 6.0.2 on 2026-03-16 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dimms', '0021_remove_estoque_monthly_consumption_contrato_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='estoque',
            name='monthly_consumption',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Consumo Mensal'),
        ),
    ]
