# Generated by Django 6.0.2 on 2026-08-04 16:07

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dimms', '0021_solicitacao_numero_pe_integrado'),
    ]

    operations = [
        migrations.AddField(
            model_name='bensconsumo',
            name='preco_medio',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Preço Médio'),
        ),
    ]
