# Generated by Django 6.0.2 on 2026-08-07 14:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dimms', '0022_bensconsumo_preco_medio'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='conferenciaestoque',
            name='decidido_em',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Decidido em'),
        ),
        migrations.AddField(
            model_name='conferenciaestoque',
            name='decidido_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ajustes_estoque_decididos', to=settings.AUTH_USER_MODEL, verbose_name='Decidido por'),
        ),
        migrations.AddField(
            model_name='conferenciaestoque',
            name='decisao_ajuste',
            field=models.CharField(choices=[('PENDENTE', 'Pendente'), ('APROVADO', 'Aprovado'), ('REJEITADO', 'Rejeitado')], default='PENDENTE', max_length=15, verbose_name='Decisão do Ajuste'),
        ),
    ]
