# Generated by Django 6.0.2 on 2026-03-18 12:02

import dimms.utils
import django.core.validators
import django.db.models.deletion
import localflavor.br.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dimms', '0022_estoque_monthly_consumption'),
    ]

    operations = [
        migrations.CreateModel(
            name='Artifacts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('artifacts_code', models.CharField(blank=True, editable=False, max_length=50, unique=True, verbose_name='Artefato')),
                ('description', models.CharField(blank=True, max_length=100, verbose_name='Descrição')),
                ('tr', models.FileField(blank=True, upload_to=dimms.utils.path_tr, verbose_name='(TR) Termo de Referência')),
                ('etp', models.FileField(blank=True, upload_to=dimms.utils.path_etp, verbose_name='(ETP) Estudo Técnico Preeliminar')),
                ('rgpp', models.FileField(blank=True, upload_to=dimms.utils.path_rgpp, verbose_name='(RGPP) Registro de Preço')),
                ('dode', models.FileField(blank=True, upload_to=dimms.utils.path_dode, verbose_name='(DODE)Documento de Oficialização de Demanda')),
                ('tapp', models.FileField(blank=True, upload_to=dimms.utils.path_tapp, verbose_name='(TAPP) TERMO DE ANALISE PREELIMINAR DO PLANEJAMENTO DA CONTRATAÇÃO')),
                ('risk_analysis', models.FileField(blank=True, upload_to=dimms.utils.path_risk_analysis, verbose_name='Análise de Risco')),
                ('state', models.CharField(blank=True, verbose_name='Estado')),
            ],
            options={
                'verbose_name': 'Artefato',
                'verbose_name_plural': 'Artefatos',
            },
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('supplier', models.CharField(max_length=40, verbose_name='Fornecedor')),
                ('cnpj_supplier', localflavor.br.models.BRCNPJField(blank=True, max_length=18, null=True, verbose_name='CNPJ do Fornecedor')),
                ('contact_supplier', models.CharField(blank=True, max_length=15, null=True, validators=[django.core.validators.RegexValidator(regex='^\\+?\\d{10,15}$')], verbose_name='Contato do Fornecedor')),
                ('email_supplier', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email do Fornecedor')),
            ],
            options={
                'verbose_name': 'Fornecedor',
                'verbose_name_plural': '02 - Fonecedores',
            },
        ),
        migrations.RemoveField(
            model_name='contrato',
            name='fornecedor',
        ),
        migrations.CreateModel(
            name='ItensArtifacts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('details', models.TextField(blank=True, verbose_name='Detalhamento do Item')),
                ('amount', models.PositiveIntegerField(blank=True, verbose_name='Quantidade')),
                ('value_max', models.PositiveIntegerField(blank=True, verbose_name='Valor Máximo')),
                ('artifacts', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='dimms.artifacts', verbose_name='Itens do Artefato')),
                ('efisco', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, to='dimms.bensconsumo', verbose_name='Efisco')),
            ],
            options={
                'verbose_name': 'Item Artefato',
                'verbose_name_plural': 'Itens Artefatos',
            },
        ),
        migrations.CreateModel(
            name='Proposal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('proposal_code', models.CharField(blank=True, editable=False, max_length=50, unique=True, verbose_name='Proposta')),
                ('state', models.CharField(blank=True, max_length=30, verbose_name='Estado')),
                ('artifacts_proposal', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='dimms.artifacts', verbose_name='Artefato')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='dimms.supplier', verbose_name='Fornecedor')),
            ],
            options={
                'verbose_name': 'Proposta',
                'verbose_name_plural': 'Propostas',
            },
        ),
        migrations.CreateModel(
            name='ItensProposal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('details_proposal', models.TextField(verbose_name='Detalhes da Proposta')),
                ('amount', models.PositiveIntegerField(verbose_name='Quantidade')),
                ('value', models.PositiveIntegerField(verbose_name='Valor')),
                ('state', models.CharField(blank=True, choices=[('ANALISE', 'Em Análise'), ('APROVADO', 'Aprovado'), ('RECUSADO', 'Recusado')], max_length=50, verbose_name='Status')),
                ('reason', models.TextField(verbose_name='Motivo da Reprovação')),
                ('efisco', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='dimms.bensconsumo', verbose_name='Efisco')),
                ('proposal_item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='dimms.proposal', verbose_name='Proposta')),
            ],
            options={
                'verbose_name': 'Item Proposta',
                'verbose_name_plural': 'Itens Propostas',
            },
        ),
        migrations.AddField(
            model_name='contrato',
            name='supplier_contract',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='dimms.supplier'),
        ),
        migrations.DeleteModel(
            name='CompraIndividual',
        ),
        migrations.DeleteModel(
            name='Fornecedor',
        ),
    ]
