# Generated by Django 6.0.2 on 2026-08-07 14:27

import localflavor.br.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dimms', '0023_conferenciaestoque_decidido_em_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tramitacao',
            name='cpf_recebedor',
            field=localflavor.br.models.BRCPFField(blank=True, max_length=14, verbose_name='CPF de Quem Recebeu'),
        ),
        migrations.AddField(
            model_name='tramitacao',
            name='empresa_orgao_recebedor',
            field=models.CharField(blank=True, max_length=100, verbose_name='Empresa/Órgão de Quem Recebeu'),
        ),
        migrations.AddField(
            model_name='tramitacao',
            name='matricula_recebedor',
            field=models.CharField(blank=True, max_length=20, verbose_name='Matrícula de Quem Recebeu'),
        ),
    ]
