# Generated by Django 6.0.2 on 2026-03-18 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dimms', '0023_artifacts_supplier_remove_contrato_fornecedor_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artifacts',
            name='state',
            field=models.CharField(blank=True, choices=[('ELABORACAO', 'Em Elaboração'), ('COMPRAS', 'Encaminhado para GMEC'), ('REENCAMINHADO', 'Reencaminhado para Elaboração'), ('LICITACAO', 'Em Licitação'), ('ANALISE', 'Em Análise das Propostas'), ('VENCEDORA', 'Encaminhado Vencedora'), ('HOMOLOGADO', 'Homologado')], max_length=40, verbose_name='Estado'),
        ),
    ]
