# Generated by Django 6.0.2 on 2026-08-11 15:19

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dimms', '0024_tramitacao_cpf_recebedor_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AditivoContrato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(editable=False, max_length=30, unique=True, verbose_name='Número do Aditivo')),
                ('numero_empenho', models.CharField(blank=True, max_length=60, verbose_name='N° Empenho')),
                ('valor_acrescido', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True, verbose_name='Valor Acrescido (R$)')),
                ('observacao', models.TextField(blank=True, verbose_name='Observação')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('contrato', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='aditivos', to='dimms.contrato', verbose_name='Contrato')),
                ('criado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='aditivos_criados', to=settings.AUTH_USER_MODEL, verbose_name='Criado por')),
            ],
            options={
                'verbose_name': 'Aditivo de Contrato',
                'verbose_name_plural': '14 - Aditivos de Contrato',
                'ordering': ['-criado_em'],
            },
        ),
        migrations.CreateModel(
            name='ItemAditivoContrato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade_acrescida', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0.01)], verbose_name='Quantidade Acrescida')),
                ('item_novo', models.BooleanField(default=False, verbose_name='Item novo no contrato')),
                ('aditivo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens', to='dimms.aditivocontrato', verbose_name='Aditivo')),
                ('efisco', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='itens_aditivo', to='dimms.bensconsumo', verbose_name='Efisco')),
            ],
            options={
                'verbose_name': 'Item de Aditivo',
                'verbose_name_plural': '15 - Itens de Aditivo',
            },
        ),
    ]
