# Generated by Django 6.0.2 on 2026-03-18 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dimms', '0024_alter_artifacts_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itensproposal',
            name='reason',
            field=models.TextField(blank=True, verbose_name='Motivo da Reprovação'),
        ),
        migrations.AlterField(
            model_name='proposal',
            name='state',
            field=models.CharField(blank=True, choices=[('ANALISE', 'Em Análise'), ('APROVADO', 'Aprovado'), ('RECUSADO', 'Recusado')], max_length=30, verbose_name='Estado'),
        ),
    ]
