# Generated by Django 6.0.2 on 2026-03-18 12:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dimms', '0025_alter_itensproposal_reason_alter_proposal_state'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='artifacts',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Última modificação'),
        ),
        migrations.AddField(
            model_name='artifacts',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='artifacts_updated', to=settings.AUTH_USER_MODEL, verbose_name='Última edição por'),
        ),
    ]
