# Generated by Django 6.0.2 on 2026-08-11 15:42

import dimms.utils
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dimms', '0025_aditivocontrato_itemaditivocontrato'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aditivocontrato',
            name='observacao',
        ),
        migrations.RemoveField(
            model_name='aditivocontrato',
            name='valor_acrescido',
        ),
        migrations.AddField(
            model_name='aditivocontrato',
            name='documento',
            field=models.FileField(blank=True, null=True, upload_to=dimms.utils.path_documento_aditivo, verbose_name='Documento'),
        ),
        migrations.AddField(
            model_name='itemaditivocontrato',
            name='preco_unitario',
            field=models.DecimalField(decimal_places=4, default=0.01, max_digits=12, validators=[django.core.validators.MinValueValidator(0.01)], verbose_name='Preço Unitário (R$)'),
            preserve_default=False,
        ),
    ]
