# Generated by Django 6.0.2 on 2026-03-19 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dimms', '0026_artifacts_updated_at_artifacts_updated_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='artifacts',
            name='sei',
            field=models.CharField(blank=True, max_length=50, verbose_name='SEI'),
        ),
    ]
