# Generated by Django 6.0.2 on 2026-08-14 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dimms', '0026_remove_aditivocontrato_observacao_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tramitacao',
            name='cpf_recebedor',
        ),
        migrations.AddField(
            model_name='tramitacao',
            name='cargo_recebedor',
            field=models.CharField(blank=True, max_length=100, verbose_name='Cargo/Função de Quem Recebeu'),
        ),
    ]
