# Generated by Django 6.0.2 on 2026-03-20 16:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dimms', '0027_artifacts_sei'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='estoque',
            name='form_input',
            field=models.CharField(blank=True, max_length=30, verbose_name='Forma de Entrada'),
        ),
        migrations.AddField(
            model_name='estoque',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='Última modificação'),
        ),
        migrations.AddField(
            model_name='estoque',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stock_updated', to=settings.AUTH_USER_MODEL, verbose_name='Última edição por'),
        ),
    ]
