# Generated by Django 6.0.2 on 2026-08-14 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dimms', '0027_remove_tramitacao_cpf_recebedor_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estoque',
            name='method',
            field=models.TextField(blank=True, verbose_name='Método de Entrada'),
        ),
    ]
