# Generated by Django 6.0.2 on 2026-04-23 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('dempam', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='managed_uas',
            field=models.ManyToManyField(blank=True, related_name='managers', to='dempam.infoua', verbose_name='UAs que gerencia'),
        ),
        migrations.AddField(
            model_name='profile',
            name='uas',
            field=models.ManyToManyField(blank=True, related_name='members', to='dempam.infoua', verbose_name='UAs que pertence'),
        ),
    ]
