# Generated by Django 6.0.2 on 2026-07-06 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_feedback_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='imagem',
            field=models.ImageField(blank=True, null=True, upload_to='feedback/', verbose_name='Print'),
        ),
    ]
