# Generated by Django 6.0.2 on 2026-07-13 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_feedback_imagem'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='status',
            field=models.CharField(choices=[('ABERTO', 'Aberto'), ('EM_ANDAMENTO', 'Em Andamento'), ('ATENDIDO', 'Atendido'), ('RECUSADO', 'Recusado')], default='ABERTO', max_length=15, verbose_name='Status'),
        ),
    ]
