# Generated by Django 6.0.2 on 2026-07-13 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_feedback_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='codigo',
            field=models.CharField(blank=True, editable=False, max_length=30, null=True, unique=True, verbose_name='Código'),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='status',
            field=models.CharField(choices=[('ABERTO', 'Aberto'), ('EM_ANDAMENTO', 'Em Andamento'), ('FINALIZADO', 'Finalizado'), ('RECUSADO', 'Recusado')], default='ABERTO', max_length=15, verbose_name='Status'),
        ),
    ]
