# Generated by Django 6.0.2 on 2026-07-13 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_feedback_codigo_alter_feedback_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='resolucao',
            field=models.TextField(blank=True, verbose_name='O que foi feito'),
        ),
    ]
