# Generated by Django 6.0.2 on 2026-07-13 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_feedback_resolucao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='status',
            field=models.CharField(choices=[('ABERTO', 'Aberto'), ('EM_ANDAMENTO', 'Em Andamento'), ('FINALIZADO', 'Finalizada'), ('RECUSADO', 'Recusada')], default='ABERTO', max_length=15, verbose_name='Status'),
        ),
    ]
