# Generated by Django 6.0.2 on 2026-07-23 14:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_alter_feedback_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RegistroAcesso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateTimeField(auto_now_add=True, verbose_name='Data e Hora do Acesso')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registros_acesso', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Registro de Acesso',
                'verbose_name_plural': 'Registros de Acesso',
                'ordering': ['-data'],
            },
        ),
    ]
