# Generated by Django 6.0.2 on 2026-04-23 12:54

import demands.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Demand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(editable=False, max_length=20, unique=True, verbose_name='Código')),
                ('title', models.CharField(max_length=120, verbose_name='Título')),
                ('description', models.TextField(verbose_name='Descrição')),
                ('priority', models.CharField(choices=[('low', 'Baixa'), ('medium', 'Média'), ('high', 'Alta'), ('urgent', 'Urgente')], default='medium', max_length=10, verbose_name='Prioridade')),
                ('status', models.CharField(choices=[('open', 'Aberta'), ('in_progress', 'Em Andamento'), ('done', 'Concluída')], default='open', max_length=15, verbose_name='Status')),
                ('deadline', models.DateField(blank=True, null=True, verbose_name='Prazo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('assigned_to', models.ManyToManyField(blank=True, related_name='demands_assigned', to=settings.AUTH_USER_MODEL, verbose_name='Atribuído a')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='demands_created', to=settings.AUTH_USER_MODEL, verbose_name='Criado por')),
            ],
            options={
                'verbose_name': 'Demanda',
                'verbose_name_plural': 'Demandas',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DemandAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to=demands.models.demand_attachment_path, verbose_name='Arquivo')),
                ('name', models.CharField(blank=True, max_length=120, verbose_name='Nome do arquivo')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='Enviado em')),
                ('demand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='demands.demand', verbose_name='Demanda')),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Enviado por')),
            ],
            options={
                'verbose_name': 'Anexo',
                'verbose_name_plural': 'Anexos',
            },
        ),
        migrations.CreateModel(
            name='DemandType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, unique=True, verbose_name='Nome')),
                ('description', models.TextField(blank=True, verbose_name='Descrição')),
                ('color', models.CharField(default='#1d4ed8', max_length=7, verbose_name='Cor')),
                ('icon', models.CharField(default='📋', max_length=10, verbose_name='Ícone')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('allowed_groups', models.ManyToManyField(blank=True, related_name='demand_types', to='auth.group', verbose_name='Grupos com permissão para criar')),
            ],
            options={
                'verbose_name': 'Tipo de Demanda',
                'verbose_name_plural': 'Tipos de Demanda',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='demand',
            name='demand_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='demands.demandtype', verbose_name='Tipo'),
        ),
        migrations.CreateModel(
            name='DemandUpdate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField(verbose_name='Comentário')),
                ('status_change', models.CharField(blank=True, choices=[('open', 'Aberta'), ('in_progress', 'Em Andamento'), ('done', 'Concluída')], max_length=15, verbose_name='Mudança de status')),
                ('file', models.FileField(blank=True, null=True, upload_to=demands.models.update_attachment_path, verbose_name='Arquivo anexado')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Postado em')),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Autor')),
                ('demand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='updates', to='demands.demand', verbose_name='Demanda')),
            ],
            options={
                'verbose_name': 'Atualização',
                'verbose_name_plural': 'Atualizações',
                'ordering': ['created_at'],
            },
        ),
    ]
