# Generated by Django 6.0.2 on 2026-04-23 13:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demands', '0001_initial'),
        ('dempam', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='demand',
            name='ua',
            field=models.ForeignKey(blank=True, help_text='Unidade Administrativa responsável pela demanda', null=True, on_delete=django.db.models.deletion.PROTECT, to='dempam.infoua', verbose_name='UA'),
        ),
    ]
