# Generated by Django 6.0.2 on 2026-07-03 15:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('demands', '0003_demandassignment'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='demand',
            options={'ordering': ['-created_at'], 'verbose_name': 'Demanda', 'verbose_name_plural': '02 - Demandas'},
        ),
        migrations.AlterModelOptions(
            name='demandassignment',
            options={'verbose_name': 'Atribuição', 'verbose_name_plural': '03 - Atribuições'},
        ),
        migrations.AlterModelOptions(
            name='demandattachment',
            options={'verbose_name': 'Anexo', 'verbose_name_plural': '04 - Anexos'},
        ),
        migrations.AlterModelOptions(
            name='demandtype',
            options={'ordering': ['name'], 'verbose_name': 'Tipo de Demanda', 'verbose_name_plural': '01 - Tipos de Demanda'},
        ),
        migrations.AlterModelOptions(
            name='demandupdate',
            options={'ordering': ['created_at'], 'verbose_name': 'Atualização', 'verbose_name_plural': '05 - Atualizações'},
        ),
    ]
