# Generated by Django 5.2.6 on 2025-09-15 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('numero_identificacao', models.IntegerField(primary_key=True, serialize=False, unique=True, verbose_name='Número de Identificação')),
                ('nome', models.CharField(max_length=200, verbose_name='Nome do Item')),
                ('descricao', models.TextField(blank=True, verbose_name='Descrição')),
                ('localizacao', models.CharField(blank=True, max_length=100, verbose_name='Localização')),
                ('data_cadastro', models.DateTimeField(auto_now_add=True, verbose_name='Data de Cadastro')),
            ],
        ),
    ]
