# Generated by Django 5.2.6 on 2025-09-16 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itens', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='centro_de_custo',
            field=models.CharField(blank=True, max_length=100, verbose_name='Centro de Custo (UA)'),
        ),
        migrations.AddField(
            model_name='item',
            name='cnpj_fornecedor',
            field=models.CharField(blank=True, max_length=20, verbose_name='CNPJ do Fornecedor'),
        ),
        migrations.AddField(
            model_name='item',
            name='codigo_efisco',
            field=models.CharField(blank=True, max_length=100, verbose_name='Código do E-FISCO'),
        ),
        migrations.AddField(
            model_name='item',
            name='data_aquisicao',
            field=models.DateField(blank=True, null=True, verbose_name='Data de Aquisição'),
        ),
        migrations.AddField(
            model_name='item',
            name='estado_de_conservacao',
            field=models.CharField(blank=True, max_length=100, verbose_name='Estado de Conservação'),
        ),
        migrations.AddField(
            model_name='item',
            name='fabricante',
            field=models.CharField(blank=True, max_length=100, verbose_name='Fabricante'),
        ),
        migrations.AddField(
            model_name='item',
            name='forma_de_ingresso',
            field=models.CharField(blank=True, max_length=100, verbose_name='Forma de Ingresso'),
        ),
        migrations.AddField(
            model_name='item',
            name='foto_do_bem',
            field=models.ImageField(blank=True, null=True, upload_to='fotos_itens/', verbose_name='Foto do Bem'),
        ),
        migrations.AddField(
            model_name='item',
            name='garantia_em_dias',
            field=models.IntegerField(default=0, verbose_name='Garantia (em dias)'),
        ),
        migrations.AddField(
            model_name='item',
            name='marca',
            field=models.CharField(blank=True, max_length=100, verbose_name='Marca'),
        ),
        migrations.AddField(
            model_name='item',
            name='mat_responsavel_ua',
            field=models.CharField(blank=True, max_length=100, verbose_name='Matrícula Responsável UA'),
        ),
        migrations.AddField(
            model_name='item',
            name='modelo',
            field=models.CharField(blank=True, max_length=100, verbose_name='Modelo'),
        ),
        migrations.AddField(
            model_name='item',
            name='numero_de_serie',
            field=models.CharField(blank=True, max_length=100, verbose_name='Número de Série'),
        ),
        migrations.AddField(
            model_name='item',
            name='numero_do_documento',
            field=models.CharField(blank=True, max_length=100, verbose_name='Número do Documento'),
        ),
        migrations.AddField(
            model_name='item',
            name='observacao',
            field=models.TextField(blank=True, verbose_name='Observação'),
        ),
        migrations.AddField(
            model_name='item',
            name='responsavel_ua',
            field=models.CharField(blank=True, max_length=200, verbose_name='Responsável UA'),
        ),
        migrations.AddField(
            model_name='item',
            name='situacao_fisica',
            field=models.CharField(blank=True, max_length=100, verbose_name='Situação Física'),
        ),
        migrations.AddField(
            model_name='item',
            name='situacao_juridica',
            field=models.CharField(blank=True, max_length=100, verbose_name='Situação Jurídica'),
        ),
        migrations.AddField(
            model_name='item',
            name='tipo_do_bem',
            field=models.CharField(blank=True, max_length=100, verbose_name='Tipo do Bem'),
        ),
        migrations.AddField(
            model_name='item',
            name='tipo_do_documento',
            field=models.CharField(blank=True, max_length=100, verbose_name='Tipo do Documento'),
        ),
        migrations.AddField(
            model_name='item',
            name='valor_unitario',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Valor Unitário'),
        ),
        migrations.AlterField(
            model_name='item',
            name='data_cadastro',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Data de Cadastro no Sistema'),
        ),
        migrations.AlterField(
            model_name='item',
            name='numero_identificacao',
            field=models.IntegerField(primary_key=True, serialize=False, unique=True, verbose_name='Tombo / Número de Identificação'),
        ),
    ]
