# Generated by Django 5.2.6 on 2025-09-17 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itens', '0002_item_centro_de_custo_item_cnpj_fornecedor_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='lote',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Identificador do Lote'),
        ),
    ]
