# Generated by Django 5.2.6 on 2025-09-17 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itens', '0003_item_lote'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='responsavel_ua',
        ),
        migrations.AddField(
            model_name='item',
            name='classe',
            field=models.CharField(blank=True, max_length=100, verbose_name='Classe'),
        ),
        migrations.AddField(
            model_name='item',
            name='cod_natureza_de_despesa',
            field=models.CharField(blank=True, max_length=100, verbose_name='Cód. Natureza de Despesa'),
        ),
        migrations.AddField(
            model_name='item',
            name='conta_contabil',
            field=models.CharField(blank=True, max_length=100, verbose_name='Conta Contábil'),
        ),
        migrations.AddField(
            model_name='item',
            name='data_da_entrega',
            field=models.DateField(blank=True, null=True, verbose_name='Data da Entrega'),
        ),
        migrations.AddField(
            model_name='item',
            name='descricao_manual',
            field=models.CharField(blank=True, max_length=255, verbose_name='Descrição Manual'),
        ),
        migrations.AddField(
            model_name='item',
            name='descricao_sicap',
            field=models.CharField(blank=True, max_length=255, verbose_name='Descrição SICAP'),
        ),
        migrations.AddField(
            model_name='item',
            name='mat_resp_ua_ext',
            field=models.CharField(blank=True, max_length=100, verbose_name='Matrícula Responsável UA Externo'),
        ),
        migrations.AddField(
            model_name='item',
            name='modalidade',
            field=models.CharField(blank=True, max_length=100, verbose_name='Modalidade'),
        ),
        migrations.AddField(
            model_name='item',
            name='moeda',
            field=models.CharField(blank=True, default='BRL', max_length=50, verbose_name='Moeda'),
        ),
        migrations.AddField(
            model_name='item',
            name='nome_resp_ua_ext',
            field=models.CharField(blank=True, max_length=200, verbose_name='Nome Responsável UA Externo'),
        ),
        migrations.AddField(
            model_name='item',
            name='nome_responsavel_ua',
            field=models.CharField(blank=True, max_length=200, verbose_name='Nome Responsável UA'),
        ),
        migrations.AddField(
            model_name='item',
            name='numero_da_af',
            field=models.CharField(blank=True, max_length=100, verbose_name='Número da AF'),
        ),
        migrations.AddField(
            model_name='item',
            name='numero_do_empenho',
            field=models.CharField(blank=True, max_length=100, verbose_name='Número do Empenho'),
        ),
        migrations.AddField(
            model_name='item',
            name='numero_do_processo',
            field=models.CharField(blank=True, max_length=100, verbose_name='Número do Processo'),
        ),
        migrations.AddField(
            model_name='item',
            name='qtde',
            field=models.IntegerField(default=1, verbose_name='Quantidade'),
        ),
        migrations.AddField(
            model_name='item',
            name='subclasse_1',
            field=models.CharField(blank=True, max_length=100, verbose_name='Subclasse 1'),
        ),
        migrations.AddField(
            model_name='item',
            name='subclasse_2',
            field=models.CharField(blank=True, max_length=100, verbose_name='Subclasse 2'),
        ),
        migrations.AddField(
            model_name='item',
            name='subclasse_3',
            field=models.CharField(blank=True, max_length=100, verbose_name='Subclasse 3'),
        ),
        migrations.AddField(
            model_name='item',
            name='tombamento_legado',
            field=models.CharField(blank=True, max_length=100, verbose_name='Tombamento Legado'),
        ),
        migrations.AddField(
            model_name='item',
            name='ua_atual',
            field=models.CharField(blank=True, max_length=100, verbose_name='UA Atual'),
        ),
        migrations.AddField(
            model_name='item',
            name='unidade_gestora',
            field=models.CharField(blank=True, max_length=100, verbose_name='Unidade Gestora'),
        ),
        migrations.AddField(
            model_name='item',
            name='venc_garantia',
            field=models.DateField(blank=True, null=True, verbose_name='Vencimento da Garantia'),
        ),
        migrations.AlterField(
            model_name='item',
            name='numero_identificacao',
            field=models.IntegerField(primary_key=True, serialize=False, unique=True, verbose_name='Tombo / Nº de Identificação'),
        ),
        migrations.AlterField(
            model_name='item',
            name='valor_unitario',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12, verbose_name='Valor Unitário'),
        ),
    ]
