# Generated by Django 5.2.6 on 2025-09-22 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itens', '0005_remove_item_centro_de_custo_remove_item_classe_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='categoria',
            field=models.CharField(choices=[('PERMANENTE', 'Bens Permanentes'), ('CONSUMO', 'Bens de Consumo'), ('TI', 'Bens de TI')], default='PERMANENTE', max_length=20, verbose_name='Categoria do Bem'),
        ),
    ]
