# Generated by Django 5.2.6 on 2025-10-01 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itens', '0006_item_categoria'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='data_de_validade',
            field=models.DateField(blank=True, null=True, verbose_name='Data de Validade'),
        ),
        migrations.AddField(
            model_name='item',
            name='quantidade_em_estoque',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Quantidade em Estoque'),
        ),
    ]
