# Generated by Django 5.2.6 on 2025-10-01 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itens', '0007_item_data_de_validade_item_quantidade_em_estoque'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='data_de_validade',
        ),
        migrations.RemoveField(
            model_name='item',
            name='quantidade_em_estoque',
        ),
        migrations.AddField(
            model_name='item',
            name='tipo_consumo',
            field=models.CharField(blank=True, choices=[('ALIMENTOS', 'Alimentos'), ('COPA-COZINHA', 'Copa-Cozinha'), ('EXPEDIENTE', 'Expediente'), ('PAPEIS PARA EXPEDIENTE', 'Papéis para Expediente'), ('ESTOCAGEM', 'Estocagem'), ('CONFECCAO', 'Confecção'), ('TONERS', 'Toners'), ('INFORMATICA', 'Informática'), ('LIMPEZA', 'Limpeza'), ('PAPEIS PARA LIMPEZA', 'Papéis para Limpeza'), ('DOMISSANITARIOS', 'Domissanitários'), ('EPI', 'EPI'), ('MANUTENCAO', 'Manutenção'), ('OUTROS', 'Outros')], max_length=50, null=True, verbose_name='Tipo de Bem de Consumo'),
        ),
    ]
