# Generated by Django 5.2.6 on 2025-10-01 16:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itens', '0008_remove_item_data_de_validade_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bloco',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(help_text='Ex: Bloco A, Prateleira 12-C, Armário da Copa', max_length=100, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='item',
            name='bloco',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='itens.bloco', verbose_name='Bloco de Armazenamento'),
        ),
    ]
