# Generated by Django 5.2.6 on 2025-10-01 18:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('itens', '0009_bloco_item_bloco'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='bloco',
        ),
    ]
