# Generated by Django 5.2.6 on 2025-10-01 18:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itens', '0010_remove_item_bloco'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='descricao',
        ),
        migrations.RemoveField(
            model_name='item',
            name='localizacao',
        ),
        migrations.RemoveField(
            model_name='item',
            name='valor_unitario',
        ),
        migrations.AddField(
            model_name='item',
            name='almoxarifado',
            field=models.CharField(blank=True, max_length=100, verbose_name='Almoxarifado'),
        ),
        migrations.AddField(
            model_name='item',
            name='bloco',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='itens.bloco', verbose_name='Bloco de Armazenamento'),
        ),
        migrations.AddField(
            model_name='item',
            name='centro_de_custo',
            field=models.CharField(blank=True, max_length=100, verbose_name='Centro de Custo (UA)'),
        ),
        migrations.AddField(
            model_name='item',
            name='cnpj_fornecedor',
            field=models.CharField(blank=True, max_length=20, verbose_name='CNPJ do Fornecedor'),
        ),
        migrations.AddField(
            model_name='item',
            name='cod_natureza_de_despesa',
            field=models.CharField(blank=True, max_length=100, verbose_name='Cód. Natureza de Despesa'),
        ),
        migrations.AddField(
            model_name='item',
            name='codigo_efisco',
            field=models.CharField(blank=True, max_length=100, verbose_name='Código do E-FISCO'),
        ),
        migrations.AddField(
            model_name='item',
            name='cons_mes_hist',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Cons. Mês Histórico'),
        ),
        migrations.AddField(
            model_name='item',
            name='consumo_mensal',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Consumo Mensal'),
        ),
        migrations.AddField(
            model_name='item',
            name='conta_contabil',
            field=models.CharField(blank=True, max_length=100, verbose_name='Conta Contábil'),
        ),
        migrations.AddField(
            model_name='item',
            name='custo_unit',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12, verbose_name='Custo Unitário'),
        ),
        migrations.AddField(
            model_name='item',
            name='data_aquisicao',
            field=models.DateField(blank=True, null=True, verbose_name='Data de Aquisição'),
        ),
        migrations.AddField(
            model_name='item',
            name='data_da_entrega',
            field=models.DateField(blank=True, null=True, verbose_name='Data da Entrega'),
        ),
        migrations.AddField(
            model_name='item',
            name='descricao_manual',
            field=models.CharField(blank=True, max_length=255, verbose_name='Descrição Manual'),
        ),
        migrations.AddField(
            model_name='item',
            name='descricao_sicap',
            field=models.CharField(blank=True, max_length=255, verbose_name='Descrição SICAP'),
        ),
        migrations.AddField(
            model_name='item',
            name='duracao',
            field=models.IntegerField(default=0, help_text='Duração estimada em dias', verbose_name='Duração'),
        ),
        migrations.AddField(
            model_name='item',
            name='endereco',
            field=models.CharField(blank=True, max_length=255, verbose_name='Endereço (Localização)'),
        ),
        migrations.AddField(
            model_name='item',
            name='fabricante',
            field=models.CharField(blank=True, max_length=100, verbose_name='Fabricante'),
        ),
        migrations.AddField(
            model_name='item',
            name='forma_de_controle',
            field=models.CharField(blank=True, max_length=100, verbose_name='Forma de Controle'),
        ),
        migrations.AddField(
            model_name='item',
            name='forma_de_ingresso',
            field=models.CharField(blank=True, max_length=100, verbose_name='Forma de Ingresso'),
        ),
        migrations.AddField(
            model_name='item',
            name='garantia_em_dias',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Garantia (em dias)'),
        ),
        migrations.AddField(
            model_name='item',
            name='imobilizado',
            field=models.CharField(blank=True, max_length=100, verbose_name='Imobilizado'),
        ),
        migrations.AddField(
            model_name='item',
            name='modalidade',
            field=models.CharField(blank=True, max_length=100, verbose_name='Modalidade'),
        ),
        migrations.AddField(
            model_name='item',
            name='moeda',
            field=models.CharField(blank=True, default='BRL', max_length=50, verbose_name='Moeda'),
        ),
        migrations.AddField(
            model_name='item',
            name='numero_da_af',
            field=models.CharField(blank=True, max_length=100, verbose_name='Número da AF'),
        ),
        migrations.AddField(
            model_name='item',
            name='numero_de_serie',
            field=models.CharField(blank=True, max_length=100, verbose_name='Número de Série'),
        ),
        migrations.AddField(
            model_name='item',
            name='numero_do_documento',
            field=models.CharField(blank=True, max_length=100, verbose_name='Número do Documento'),
        ),
        migrations.AddField(
            model_name='item',
            name='numero_do_empenho',
            field=models.CharField(blank=True, max_length=100, verbose_name='Número do Empenho'),
        ),
        migrations.AddField(
            model_name='item',
            name='numero_do_processo',
            field=models.CharField(blank=True, max_length=100, verbose_name='Número do Processo'),
        ),
        migrations.AddField(
            model_name='item',
            name='observacao',
            field=models.TextField(blank=True, verbose_name='Observação'),
        ),
        migrations.AddField(
            model_name='item',
            name='qtd_estoque',
            field=models.IntegerField(default=0, verbose_name='Qtd. em Estoque'),
        ),
        migrations.AddField(
            model_name='item',
            name='qtde',
            field=models.IntegerField(default=1, verbose_name='Quantidade'),
        ),
        migrations.AddField(
            model_name='item',
            name='responsavel_ua',
            field=models.CharField(blank=True, max_length=200, verbose_name='Responsável UA'),
        ),
        migrations.AddField(
            model_name='item',
            name='situacao_fisica',
            field=models.CharField(blank=True, max_length=100, verbose_name='Situação Física'),
        ),
        migrations.AddField(
            model_name='item',
            name='situacao_juridica',
            field=models.CharField(blank=True, max_length=100, verbose_name='Situação Jurídica'),
        ),
        migrations.AddField(
            model_name='item',
            name='tipo_do_documento',
            field=models.CharField(blank=True, max_length=100, verbose_name='Tipo do Documento'),
        ),
        migrations.AddField(
            model_name='item',
            name='titularidade',
            field=models.CharField(blank=True, max_length=100, verbose_name='Titularidade'),
        ),
        migrations.AddField(
            model_name='item',
            name='tombamento_legado',
            field=models.CharField(blank=True, max_length=100, verbose_name='Tombamento Legado'),
        ),
        migrations.AddField(
            model_name='item',
            name='unidade',
            field=models.CharField(blank=True, max_length=50, verbose_name='Unidade (Ex: pç, kg, cx)'),
        ),
        migrations.AddField(
            model_name='item',
            name='unidade_gestora',
            field=models.CharField(blank=True, max_length=100, verbose_name='Unidade Gestora'),
        ),
        migrations.AddField(
            model_name='item',
            name='validade',
            field=models.DateField(blank=True, null=True, verbose_name='Validade'),
        ),
        migrations.AddField(
            model_name='item',
            name='valor_aquisicao',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12, verbose_name='Valor de Aquisição'),
        ),
        migrations.AddField(
            model_name='item',
            name='valor_atual_do_bem',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12, verbose_name='Valor Atual do Bem'),
        ),
        migrations.AlterField(
            model_name='item',
            name='categoria',
            field=models.CharField(choices=[('PERMANENTE', 'Bens Permanentes'), ('CONSUMO', 'Bens de Consumo'), ('TI', 'Bens de TI')], default='PERMANENTE', max_length=20, verbose_name='Categoria Principal'),
        ),
        migrations.AlterField(
            model_name='item',
            name='numero_identificacao',
            field=models.IntegerField(primary_key=True, serialize=False, unique=True, verbose_name='Índice / Tombo'),
        ),
        migrations.AlterField(
            model_name='item',
            name='tipo_consumo',
            field=models.CharField(blank=True, choices=[('ALIMENTOS', 'Alimentos'), ('COPA-COZINHA', 'Copa-Cozinha'), ('EXPEDIENTE', 'Expediente'), ('PAPEIS PARA EXPEDIENTE', 'Papéis para Expediente'), ('ESTOCAGEM', 'Estocagem'), ('CONFECCAO', 'Confecção'), ('TONERS', 'Toners'), ('INFORMATICA', 'Informática'), ('LIMPEZA', 'Limpeza'), ('PAPEIS PARA LIMPEZA', 'Papéis para Limpeza'), ('DOMISSANITARIOS', 'Domissanitários'), ('EPI', 'EPI'), ('MANUTENCAO', 'Manutenção'), ('OUTROS', 'Outros')], max_length=50, null=True, verbose_name='Grupo (Bens de Consumo)'),
        ),
    ]
