# Generated by Django 5.2.7 on 2025-11-04 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itens', '0013_movimentacao'),
    ]

    operations = [
        migrations.AddField(
            model_name='movimentacao',
            name='documento_pdf',
            field=models.FileField(blank=True, null=True, upload_to='movimentacoes_pdf/', verbose_name='Documento (PDF)'),
        ),
    ]
