# Generated by Django 5.2.7 on 2025-11-06 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itens', '0014_movimentacao_documento_pdf'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movimentacao',
            name='documento_pdf',
            field=models.FileField(blank=True, null=True, upload_to='movimentacoes_pdf/', verbose_name='Documento (PDF/Foto)'),
        ),
    ]
