# Generated by Django 4.2.26 on 2025-11-17 17:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('itens', '0015_alter_movimentacao_documento_pdf'),
    ]

    operations = [
        migrations.CreateModel(
            name='Requisicao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.PositiveIntegerField(verbose_name='Quantidade Requisitada')),
                ('data_requisicao', models.DateTimeField(auto_now_add=True, verbose_name='Data da Requisição')),
                ('status', models.CharField(choices=[('PENDENTE', 'Pendente'), ('APROVADO', 'Aprovado'), ('REJEITADO', 'Rejeitado')], default='PENDENTE', max_length=10)),
                ('observacao', models.TextField(blank=True, null=True, verbose_name='Observação/Justificativa')),
                ('item_requisitado', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='itens.item', verbose_name='Item Requisitado')),
                ('requisitante', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Requisitante')),
            ],
            options={
                'verbose_name_plural': 'Requisições',
                'ordering': ['-data_requisicao'],
            },
        ),
    ]
