# Generated by Django 4.2.26 on 2025-11-18 16:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('itens', '0016_requisicao'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='requisicao',
            name='item_requisitado',
        ),
        migrations.RemoveField(
            model_name='requisicao',
            name='observacao',
        ),
        migrations.RemoveField(
            model_name='requisicao',
            name='quantidade',
        ),
        migrations.AddField(
            model_name='requisicao',
            name='observacao_geral',
            field=models.TextField(blank=True, null=True, verbose_name='Observação/Justificativa Geral'),
        ),
        migrations.CreateModel(
            name='ItemRequisitado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.PositiveIntegerField(verbose_name='Quantidade Requisitada')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='itens.item', verbose_name='Item Requisitado')),
                ('requisicao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens_pedidos', to='itens.requisicao')),
            ],
        ),
    ]
