# Generated by Django 4.2.26 on 2025-12-04 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itens', '0017_remove_requisicao_item_requisitado_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='valor_aquisicao',
        ),
        migrations.AddField(
            model_name='item',
            name='valor_unitario',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12, verbose_name='Valor Unitário'),
        ),
    ]
