# Generated by Django 4.2.26 on 2025-12-04 19:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('itens', '0018_remove_item_valor_aquisicao_item_valor_unitario'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='movimentacao',
            options={},
        ),
        migrations.AlterModelOptions(
            name='requisicao',
            options={},
        ),
        migrations.RemoveField(
            model_name='item',
            name='almoxarifado',
        ),
        migrations.RemoveField(
            model_name='item',
            name='centro_de_custo',
        ),
        migrations.RemoveField(
            model_name='item',
            name='cnpj_fornecedor',
        ),
        migrations.RemoveField(
            model_name='item',
            name='cod_natureza_de_despesa',
        ),
        migrations.RemoveField(
            model_name='item',
            name='cons_mes_hist',
        ),
        migrations.RemoveField(
            model_name='item',
            name='consumo_mensal',
        ),
        migrations.RemoveField(
            model_name='item',
            name='conta_contabil',
        ),
        migrations.RemoveField(
            model_name='item',
            name='custo_unit',
        ),
        migrations.RemoveField(
            model_name='item',
            name='data_aquisicao',
        ),
        migrations.RemoveField(
            model_name='item',
            name='data_da_entrega',
        ),
        migrations.RemoveField(
            model_name='item',
            name='descricao_manual',
        ),
        migrations.RemoveField(
            model_name='item',
            name='descricao_sicap',
        ),
        migrations.RemoveField(
            model_name='item',
            name='duracao',
        ),
        migrations.RemoveField(
            model_name='item',
            name='endereco',
        ),
        migrations.RemoveField(
            model_name='item',
            name='fabricante',
        ),
        migrations.RemoveField(
            model_name='item',
            name='forma_de_controle',
        ),
        migrations.RemoveField(
            model_name='item',
            name='forma_de_ingresso',
        ),
        migrations.RemoveField(
            model_name='item',
            name='garantia_em_dias',
        ),
        migrations.RemoveField(
            model_name='item',
            name='imobilizado',
        ),
        migrations.RemoveField(
            model_name='item',
            name='modalidade',
        ),
        migrations.RemoveField(
            model_name='item',
            name='moeda',
        ),
        migrations.RemoveField(
            model_name='item',
            name='numero_da_af',
        ),
        migrations.RemoveField(
            model_name='item',
            name='numero_do_documento',
        ),
        migrations.RemoveField(
            model_name='item',
            name='numero_do_empenho',
        ),
        migrations.RemoveField(
            model_name='item',
            name='numero_do_processo',
        ),
        migrations.RemoveField(
            model_name='item',
            name='observacao',
        ),
        migrations.RemoveField(
            model_name='item',
            name='responsavel_ua',
        ),
        migrations.RemoveField(
            model_name='item',
            name='situacao_fisica',
        ),
        migrations.RemoveField(
            model_name='item',
            name='situacao_juridica',
        ),
        migrations.RemoveField(
            model_name='item',
            name='tipo_do_documento',
        ),
        migrations.RemoveField(
            model_name='item',
            name='titularidade',
        ),
        migrations.RemoveField(
            model_name='item',
            name='tombamento_legado',
        ),
        migrations.RemoveField(
            model_name='item',
            name='unidade',
        ),
        migrations.RemoveField(
            model_name='item',
            name='unidade_gestora',
        ),
        migrations.RemoveField(
            model_name='item',
            name='valor_atual_do_bem',
        ),
        migrations.AddField(
            model_name='item',
            name='descricao',
            field=models.TextField(blank=True, null=True, verbose_name='Descrição'),
        ),
        migrations.AddField(
            model_name='item',
            name='localizacao',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Localização'),
        ),
        migrations.AddField(
            model_name='requisicao',
            name='documento',
            field=models.FileField(blank=True, null=True, upload_to='requisicoes_docs/'),
        ),
        migrations.AddField(
            model_name='requisicao',
            name='tipo',
            field=models.CharField(choices=[('SAIDA', 'Saída'), ('ENTRADA', 'Entrada')], default='SAIDA', max_length=10),
        ),
        migrations.AlterField(
            model_name='bloco',
            name='nome',
            field=models.CharField(help_text='Ex: Bloco A, Prateleira 12-C', max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='categoria',
            field=models.CharField(choices=[('PERMANENTE', 'Bens Permanentes'), ('CONSUMO', 'Bens de Consumo'), ('TI', 'Bens de TI')], default='PERMANENTE', max_length=20, verbose_name='Categoria do Bem'),
        ),
        migrations.AlterField(
            model_name='item',
            name='codigo_efisco',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Código do E-FISCO'),
        ),
        migrations.AlterField(
            model_name='item',
            name='data_cadastro',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='estado_de_conservacao',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Estado de Conservação'),
        ),
        migrations.AlterField(
            model_name='item',
            name='marca',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Marca'),
        ),
        migrations.AlterField(
            model_name='item',
            name='modelo',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Modelo'),
        ),
        migrations.AlterField(
            model_name='item',
            name='numero_de_serie',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Número de Série'),
        ),
        migrations.AlterField(
            model_name='item',
            name='numero_identificacao',
            field=models.IntegerField(primary_key=True, serialize=False, unique=True, verbose_name='Tombo / Nº de Identificação'),
        ),
        migrations.AlterField(
            model_name='item',
            name='qtd_estoque',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Quantidade em Estoque'),
        ),
        migrations.AlterField(
            model_name='item',
            name='qtde',
            field=models.IntegerField(default=1, verbose_name='Quantidade Total'),
        ),
        migrations.AlterField(
            model_name='item',
            name='tipo_consumo',
            field=models.CharField(blank=True, choices=[('ALIMENTOS', 'Alimentos'), ('COPA-COZINHA', 'Copa-Cozinha'), ('EXPEDIENTE', 'Expediente'), ('PAPEIS PARA EXPEDIENTE', 'Papéis para Expediente'), ('ESTOCAGEM', 'Estocagem'), ('CONFECCAO', 'Confecção'), ('TONERS', 'Toners'), ('INFORMATICA', 'Informática'), ('LIMPEZA', 'Limpeza'), ('PAPEIS PARA LIMPEZA', 'Papéis para Limpeza'), ('DOMISSANITARIOS', 'Domissanitários'), ('EPI', 'EPI'), ('MANUTENCAO', 'Manutenção'), ('OUTROS', 'Outros')], max_length=50, null=True, verbose_name='Tipo de Bem de Consumo'),
        ),
        migrations.AlterField(
            model_name='item',
            name='validade',
            field=models.DateField(blank=True, null=True, verbose_name='Data de Validade'),
        ),
        migrations.AlterField(
            model_name='item',
            name='valor_unitario',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Valor Unitário'),
        ),
        migrations.AlterField(
            model_name='itemrequisitado',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='itens.item'),
        ),
        migrations.AlterField(
            model_name='itemrequisitado',
            name='quantidade',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='movimentacao',
            name='documento_pdf',
            field=models.FileField(blank=True, null=True, upload_to='movimentacoes_pdf/'),
        ),
        migrations.AlterField(
            model_name='movimentacao',
            name='tipo',
            field=models.CharField(choices=[('ENTRADA', 'Entrada'), ('SAIDA', 'Saída')], max_length=10),
        ),
        migrations.AlterField(
            model_name='requisicao',
            name='data_requisicao',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='requisicao',
            name='observacao_geral',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='requisicao',
            name='requisitante',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
