# Generated by Django 6.0.2 on 2026-02-08 23:48

import django.core.validators
import django.db.models.deletion
import localflavor.br.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GrupoConsumo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('grupo', models.CharField(max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='InfoUA',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('ua', models.CharField(max_length=100, verbose_name='UA')),
                ('contato_ua', models.CharField(blank=True, max_length=15, null=True, validators=[django.core.validators.RegexValidator(regex='^\\+?\\d{10,15}$')], verbose_name='Contato da UA')),
                ('responsavel_ua', models.CharField(blank=True, max_length=60, null=True, verbose_name='Responsável da UA')),
                ('mat_resp_ua', models.IntegerField(blank=True, null=True, verbose_name='Matrícula do Responsável da UA')),
                ('email_ua', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email da UA')),
            ],
        ),
        migrations.CreateModel(
            name='Locais',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('local', models.CharField(max_length=80, verbose_name='Local')),
            ],
        ),
        migrations.CreateModel(
            name='BensConsumo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('efisco', models.CharField(max_length=20, verbose_name='E-Fisco')),
                ('marca', models.CharField(blank=True, max_length=30, null=True, verbose_name='Marca')),
                ('validade', models.DateField(blank=True, null=True, verbose_name='Validade')),
                ('custo_unit', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Custo Unitário')),
                ('medida', models.CharField(max_length=20, verbose_name='Unidade de Medida')),
                ('quantidade', models.IntegerField(blank=True, default=0, null=True)),
                ('grupo_consumo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='grupos_de_consumo', to='sipat.grupoconsumo', verbose_name='Grupo')),
            ],
        ),
        migrations.CreateModel(
            name='BensPermanentes',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('descricao', models.CharField(blank=True, editable=False, max_length=100, null=True, verbose_name='Descrição')),
                ('forma_de_controle', models.CharField(default='Individual', max_length=15, verbose_name='Forma de Controle')),
                ('tipo_de_bem', models.CharField(default='Móvel', max_length=15, verbose_name='Tipo do Bem')),
                ('imobilizado', models.BooleanField(default=True, verbose_name='Imobilizado')),
                ('marca_fabricante', models.CharField(blank=True, max_length=30, null=True, verbose_name='Marca/Fabricante')),
                ('modelo', models.CharField(blank=True, max_length=60, null=True, verbose_name='Modelo')),
                ('numero_de_serie', models.CharField(blank=True, max_length=30, null=True, verbose_name='Número de Série')),
                ('situacao_juridica', models.CharField(default='Regular', max_length=15, verbose_name='Situação Jurídica')),
                ('situacao_fisica', models.CharField(blank=True, max_length=20, null=True, verbose_name='Situação Física')),
                ('estado_de_conservacao', models.CharField(blank=True, max_length=20, null=True, verbose_name='Estado de Conservação')),
                ('forma_de_ingresso', models.CharField(default='Compra', max_length=15, verbose_name='Forma de Ingresso')),
                ('nota_fiscal', models.CharField(blank=True, null=True, verbose_name='Nota Fiscal')),
                ('tipo_do_documento', models.CharField(default='Nota Fiscal', max_length=20, verbose_name='Tipo do Documento')),
                ('codigo_unidade', models.CharField(default='320101', editable=False, max_length=10, verbose_name='Código da Unidade')),
                ('cpf_fornecedor', localflavor.br.models.BRCPFField(blank=True, max_length=14, null=True, verbose_name='CPF do Fornecedor')),
                ('cnpj_fornecedor', localflavor.br.models.BRCNPJField(blank=True, max_length=18, null=True, verbose_name='CNPJ do Fornecedor')),
                ('data_aquisicao', models.DateField(blank=True, null=True, verbose_name='Data da aquisição')),
                ('modalidade', models.CharField(default='Pregão Eletrônico', max_length=25, verbose_name='Modalidade')),
                ('numero_do_processo', models.CharField(blank=True, max_length=20, null=True, verbose_name='Número do Processo')),
                ('codigo_natureza_de_despesa', models.CharField(blank=True, max_length=20, null=True, verbose_name='Código Natureza de Despesa')),
                ('moeda', models.CharField(default='REAL', editable=False, max_length=5, verbose_name='Moeda')),
                ('numero_da_af', models.CharField(blank=True, max_length=20, null=True, verbose_name='Número da AF')),
                ('numero_do_empenho', models.CharField(blank=True, max_length=20, null=True, verbose_name='Número do Empenho')),
                ('garantia_em_dias', models.DateField(blank=True, null=True, verbose_name='Garantia em Dias')),
                ('valor_unitario', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=12, null=True, verbose_name='Valor Unitário')),
                ('qtde', models.IntegerField(verbose_name='Quantidade')),
                ('observacao', models.CharField(blank=True, max_length=80, null=True, verbose_name='Observação')),
                ('conta_contabil', models.CharField(blank=True, default='Ativo Móveis', max_length=20, null=True, verbose_name='Conta Contábil')),
                ('tombamento_legado', models.IntegerField(blank=True, null=True, unique=True, verbose_name='Tombamento Legado')),
                ('matricula_responsavel', models.IntegerField(verbose_name='Matrícula Responsável')),
                ('nome_responsavel', models.CharField(max_length=90, verbose_name='Nome Responsável')),
                ('valor_atual_do_bem', models.DecimalField(blank=True, decimal_places=2, default=0, editable=False, max_digits=12, null=True, verbose_name='Valor Atual do Bem')),
                ('descricao_manual', models.CharField(blank=True, max_length=30, null=True, verbose_name='Descrição Manual')),
                ('classe', models.CharField(blank=True, max_length=30, null=True, verbose_name='Classe')),
                ('subclasse', models.CharField(blank=True, max_length=30, null=True, verbose_name='Subclasse')),
                ('subclasse_2', models.CharField(blank=True, max_length=30, null=True, verbose_name='Subclasse 2')),
                ('subclasse_3', models.CharField(blank=True, max_length=30, null=True, verbose_name='Subclasse 3')),
                ('venc_garantia', models.DateField(blank=True, null=True, verbose_name='Vencimento da Garantia')),
                ('nome_resp_uso_ext', models.CharField(blank=True, max_length=50, null=True, verbose_name='Nome Responsável Uso Externo')),
                ('matricula_resp_uso_ext', models.IntegerField(blank=True, null=True, verbose_name='Matrícula Responsável Uso Externo')),
                ('contato_resp_uso_ext', models.CharField(blank=True, max_length=16, null=True, validators=[django.core.validators.RegexValidator(regex='^\\+?\\d{10,15}$')], verbose_name='Contato Responsável Uso Externo')),
                ('ua_atual', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='uas_com_bens_cadastrados', to='sipat.infoua', verbose_name='UA Atual')),
                ('unidade_gestora', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='unidades_gestora_dos_bens', to='sipat.infoua', verbose_name='Unidade Gestora')),
            ],
        ),
        migrations.AddField(
            model_name='infoua',
            name='circunscricao_predio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='circunscricoes_predios', to='sipat.locais', verbose_name='Circunscricao/Prédio'),
        ),
    ]
