# Generated by Django 6.0.2 on 2026-02-09 01:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sipat', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bensconsumo',
            options={'verbose_name': 'Bem de Consumo', 'verbose_name_plural': 'Bens de Consumo'},
        ),
        migrations.AlterModelOptions(
            name='benspermanentes',
            options={'verbose_name': 'Bem Permanente', 'verbose_name_plural': 'Bens Permanentes'},
        ),
        migrations.AlterModelOptions(
            name='grupoconsumo',
            options={'verbose_name': 'Grupo de Bem de Consumo', 'verbose_name_plural': 'Grupos de Bens de Consumo'},
        ),
        migrations.AlterModelOptions(
            name='infoua',
            options={'verbose_name': 'UA', 'verbose_name_plural': 'UAs'},
        ),
        migrations.AlterModelOptions(
            name='locais',
            options={'verbose_name': 'Local', 'verbose_name_plural': 'Locais'},
        ),
    ]
