# Generated by Django 6.0.2 on 2026-02-09 01:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sipat', '0002_alter_bensconsumo_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='benspermanentes',
            name='tombamento_legado',
            field=models.IntegerField(blank=True, null=True, unique=True, verbose_name='Tombo'),
        ),
    ]
