# Generated by Django 6.0.2 on 2026-02-09 18:20

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sipat', '0003_alter_benspermanentes_tombamento_legado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bensconsumo',
            name='efisco',
            field=models.CharField(blank=True, default='Não Consta', max_length=20, verbose_name='E-Fisco'),
        ),
        migrations.AlterField(
            model_name='bensconsumo',
            name='grupo_consumo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='grupos_de_consumo', to='sipat.grupoconsumo', verbose_name='Grupo'),
        ),
        migrations.AlterField(
            model_name='bensconsumo',
            name='marca',
            field=models.CharField(blank=True, default='S/Marca', max_length=30, verbose_name='Marca'),
        ),
        migrations.AlterField(
            model_name='benspermanentes',
            name='codigo_natureza_de_despesa',
            field=models.CharField(blank=True, default='S/Número', max_length=20, verbose_name='Código Natureza de Despesa'),
        ),
        migrations.AlterField(
            model_name='benspermanentes',
            name='codigo_unidade',
            field=models.CharField(blank=True, default='320101', editable=False, max_length=10, verbose_name='Código da Unidade'),
        ),
        migrations.AlterField(
            model_name='benspermanentes',
            name='conta_contabil',
            field=models.CharField(blank=True, default='Ativo Móveis', max_length=20, verbose_name='Conta Contábil'),
        ),
        migrations.AlterField(
            model_name='benspermanentes',
            name='descricao',
            field=models.CharField(blank=True, default='Não Consta', editable=False, max_length=100, verbose_name='Descrição'),
        ),
        migrations.AlterField(
            model_name='benspermanentes',
            name='estado_de_conservacao',
            field=models.CharField(blank=True, default='Não Consta', max_length=20, verbose_name='Estado de Conservação'),
        ),
        migrations.AlterField(
            model_name='benspermanentes',
            name='forma_de_controle',
            field=models.CharField(default='Individual', editable=False, max_length=15, verbose_name='Forma de Controle'),
        ),
        migrations.AlterField(
            model_name='benspermanentes',
            name='forma_de_ingresso',
            field=models.CharField(blank=True, default='Compra', editable=False, max_length=15, verbose_name='Forma de Ingresso'),
        ),
        migrations.AlterField(
            model_name='benspermanentes',
            name='imobilizado',
            field=models.BooleanField(default=True, editable=False, verbose_name='Imobilizado'),
        ),
        migrations.AlterField(
            model_name='benspermanentes',
            name='marca_fabricante',
            field=models.CharField(blank=True, default='Sem Marca', max_length=60, verbose_name='Marca/Fabricante'),
        ),
        migrations.AlterField(
            model_name='benspermanentes',
            name='matricula_responsavel',
            field=models.IntegerField(blank=True, default='Não Consta', verbose_name='Matrícula Responsável'),
        ),
        migrations.AlterField(
            model_name='benspermanentes',
            name='modalidade',
            field=models.CharField(blank=True, default='Pregão Eletrônico', editable=False, max_length=25, verbose_name='Modalidade'),
        ),
        migrations.AlterField(
            model_name='benspermanentes',
            name='modelo',
            field=models.CharField(blank=True, default='S/Modelo', max_length=60, verbose_name='Modelo'),
        ),
        migrations.AlterField(
            model_name='benspermanentes',
            name='nome_resp_uso_ext',
            field=models.CharField(blank=True, default='Não Consta', max_length=50, verbose_name='Nome Responsável Uso Externo'),
        ),
        migrations.AlterField(
            model_name='benspermanentes',
            name='nome_responsavel',
            field=models.CharField(blank=True, default='Não Consta', max_length=90, verbose_name='Nome Responsável'),
        ),
        migrations.AlterField(
            model_name='benspermanentes',
            name='nota_fiscal',
            field=models.CharField(blank=True, default='S/Nota Fiscal', max_length=20, verbose_name='Nota Fiscal'),
        ),
        migrations.AlterField(
            model_name='benspermanentes',
            name='numero_da_af',
            field=models.CharField(blank=True, default='S/Número', max_length=20, verbose_name='Número da AF'),
        ),
        migrations.AlterField(
            model_name='benspermanentes',
            name='numero_de_serie',
            field=models.CharField(blank=True, default='S/Número', max_length=30, verbose_name='Número de Série'),
        ),
        migrations.AlterField(
            model_name='benspermanentes',
            name='numero_do_empenho',
            field=models.CharField(blank=True, default='S/Número', max_length=20, verbose_name='Número do Empenho'),
        ),
        migrations.AlterField(
            model_name='benspermanentes',
            name='numero_do_processo',
            field=models.CharField(blank=True, default='S/Número', max_length=20, verbose_name='Número do Processo'),
        ),
        migrations.AlterField(
            model_name='benspermanentes',
            name='observacao',
            field=models.TextField(blank=True, default='', max_length=80, verbose_name='Observação'),
        ),
        migrations.AlterField(
            model_name='benspermanentes',
            name='qtde',
            field=models.IntegerField(blank=True, verbose_name='Quantidade'),
        ),
        migrations.AlterField(
            model_name='benspermanentes',
            name='situacao_fisica',
            field=models.CharField(blank=True, default='Não Consta', max_length=20, verbose_name='Situação Física'),
        ),
        migrations.AlterField(
            model_name='benspermanentes',
            name='situacao_juridica',
            field=models.CharField(default='Regular', editable=False, max_length=15, verbose_name='Situação Jurídica'),
        ),
        migrations.AlterField(
            model_name='benspermanentes',
            name='tipo_de_bem',
            field=models.CharField(default='Móvel', editable=False, max_length=15, verbose_name='Tipo do Bem'),
        ),
        migrations.AlterField(
            model_name='benspermanentes',
            name='tipo_do_documento',
            field=models.CharField(blank=True, default='Nota Fiscal', editable=False, max_length=20, verbose_name='Tipo do Documento'),
        ),
        migrations.AlterField(
            model_name='benspermanentes',
            name='valor_atual_do_bem',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, editable=False, max_digits=12, verbose_name='Valor Atual do Bem'),
        ),
        migrations.AlterField(
            model_name='infoua',
            name='contato_ua',
            field=models.CharField(blank=True, default='S/Contato', max_length=15, validators=[django.core.validators.RegexValidator(regex='^\\+?\\d{10,15}$')], verbose_name='Contato da UA'),
        ),
        migrations.AlterField(
            model_name='infoua',
            name='responsavel_ua',
            field=models.CharField(blank=True, default='Não Consta', max_length=60, verbose_name='Responsável da UA'),
        ),
    ]
