# Generated by Django 6.0.2 on 2026-02-09 19:03

import sipat.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sipat', '0004_alter_bensconsumo_efisco_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bensconsumo',
            name='imagem_consumo',
            field=models.ImageField(blank=True, null=True, upload_to=sipat.utils.caminho_bensconsumo, verbose_name='Imagem do Item'),
        ),
        migrations.AddField(
            model_name='benspermanentes',
            name='imagem_permanente',
            field=models.ImageField(blank=True, null=True, upload_to=sipat.utils.caminho_benspermanentes, verbose_name='Imagem do Bem'),
        ),
    ]
