# Generated by Django 6.0.2 on 2026-02-10 15:14

import django.db.models.deletion
import sipat.utils
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sipat', '0005_bensconsumo_imagem_consumo_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MovimentacoesPermanentes',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='SolicitacoesConsumo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('acao', models.CharField(max_length=10, verbose_name='Ação')),
                ('quantidade', models.PositiveIntegerField()),
                ('data_hora', models.DateTimeField(auto_now_add=True, verbose_name='Data e Hora da Movimentação')),
                ('observacao', models.TextField(blank=True, null=True, verbose_name='Observação')),
                ('anexo', models.FileField(blank=True, null=True, upload_to=sipat.utils.caminho_movimentacao_consumo, verbose_name='Documento Anexado')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='itens_movimentados', to='sipat.bensconsumo', verbose_name='Item Movimentado')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='usuario_mov_consumo', to=settings.AUTH_USER_MODEL, verbose_name='Usuário Responsável')),
            ],
        ),
    ]
