# Generated by Django 6.0.2 on 2026-02-10 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sipat', '0006_movimentacoespermanentes_solicitacoesconsumo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solicitacoesconsumo',
            name='acao',
            field=models.CharField(choices=[('ENTRADA', 'Entrada'), ('SAIDA', 'Saída')], max_length=10, verbose_name='Ação'),
        ),
    ]
