# Generated by Django 6.0.2 on 2026-02-10 16:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sipat', '0007_alter_solicitacoesconsumo_acao'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='solicitacoesconsumo',
            options={'verbose_name': 'Solicitação Bem de Consumo', 'verbose_name_plural': 'Solicitações Bens de Consumo'},
        ),
    ]
