# Generated by Django 6.0.2 on 2026-02-10 18:22

import django.core.validators
import django.db.models.deletion
import sipat.utils
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sipat', '0009_movimentacoesconsumo_delete_solicitacoesconsumo'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='movimentacoespermanentes',
            options={'verbose_name': 'Movimentação Permanentes', 'verbose_name_plural': 'Movimentações Permanentes'},
        ),
        migrations.RemoveField(
            model_name='benspermanentes',
            name='matricula_responsavel',
        ),
        migrations.RemoveField(
            model_name='benspermanentes',
            name='nome_responsavel',
        ),
        migrations.AddField(
            model_name='movimentacoespermanentes',
            name='acao',
            field=models.CharField(choices=[('SOLICITACAO', 'Solicitação'), ('DEVOLUCAO', 'Devolução'), ('TRANSFERENCIA', 'Transferência')], default='TRANSFERENCIA', verbose_name='Ação'),
        ),
        migrations.AddField(
            model_name='movimentacoespermanentes',
            name='anexo',
            field=models.FileField(blank=True, null=True, upload_to=sipat.utils.caminho_movimentacao_consumo, verbose_name='Documento Anexado'),
        ),
        migrations.AddField(
            model_name='movimentacoespermanentes',
            name='contato_resp_uso_ext',
            field=models.CharField(blank=True, max_length=25, null=True, validators=[django.core.validators.RegexValidator(regex='^\\+?\\d{10,15}$')], verbose_name='Contato Responsável Uso Externo'),
        ),
        migrations.AddField(
            model_name='movimentacoespermanentes',
            name='data_hora',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Data e Hora da Movimentação'),
        ),
        migrations.AddField(
            model_name='movimentacoespermanentes',
            name='destino',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='destinos_uas', to='sipat.infoua', verbose_name='Destino'),
        ),
        migrations.AddField(
            model_name='movimentacoespermanentes',
            name='matricula_resp_uso_ext',
            field=models.CharField(blank=True, default='Não Consta', max_length=25, null=True, verbose_name='Matrícula Responsável Uso Externo'),
        ),
        migrations.AddField(
            model_name='movimentacoespermanentes',
            name='nome_resp_uso_ext',
            field=models.CharField(blank=True, default='Não Consta', max_length=50, verbose_name='Nome Responsável Uso Externo'),
        ),
        migrations.AddField(
            model_name='movimentacoespermanentes',
            name='origem',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='origens_uas', to='sipat.infoua', verbose_name='Origem'),
        ),
        migrations.AddField(
            model_name='movimentacoespermanentes',
            name='sei',
            field=models.CharField(blank=True, max_length=25, null=True, verbose_name='SEI'),
        ),
        migrations.AddField(
            model_name='movimentacoespermanentes',
            name='tombo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='tombos_movimentados', to='sipat.benspermanentes', verbose_name='Tombo'),
        ),
        migrations.AddField(
            model_name='movimentacoespermanentes',
            name='usuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='usuario_mov_permanentes', to=settings.AUTH_USER_MODEL, verbose_name='Usuário Responsável'),
        ),
        migrations.AlterField(
            model_name='benspermanentes',
            name='garantia_em_dias',
            field=models.DateField(blank=True, null=True, verbose_name='Vencimento Garantia'),
        ),
        migrations.AlterField(
            model_name='benspermanentes',
            name='matricula_resp_uso_ext',
            field=models.CharField(blank=True, default='Não Consta', max_length=25, null=True, verbose_name='Matrícula Responsável Uso Externo'),
        ),
    ]
