# Generated by Django 6.0.2 on 2026-02-10 20:24

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sipat', '0010_alter_movimentacoespermanentes_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Localizacao',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('prateleira_pallet', models.CharField(blank=True, max_length=30, null=True, verbose_name='Prateleira/Pallet')),
                ('tipo_localizacao', models.CharField(blank=True, choices=[('PALLET', 'Pallet'), ('PRATELEIRA', 'Prateleira')], null=True)),
            ],
            options={
                'verbose_name': 'Localização Interna DEMPAM',
                'verbose_name_plural': 'Localizações Internas DEMPAM',
            },
        ),
        migrations.CreateModel(
            name='Setor',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('setor', models.CharField(max_length=30, verbose_name='Setor/Sala')),
            ],
            options={
                'verbose_name': 'Setor/Sala DEMPAM',
                'verbose_name_plural': 'Setores/Salas',
            },
        ),
        migrations.AlterField(
            model_name='bensconsumo',
            name='grupo_consumo',
            field=models.CharField(blank=True, choices=[('ALIMENTO', 'Alimento'), ('CONFECCAO', 'Confecção'), ('COPA_COZINHA', 'Copa / Cozinha'), ('DOMISSANITARIO', 'Domissanitário'), ('ELETRICA', 'Elétrica'), ('EPI', 'EPI'), ('HIDROSANITARIO', 'Hidrossanitário'), ('INFORMATICA', 'Informática'), ('LIMPEZA', 'Limpeza'), ('MANUTENCAO', 'Manutenção'), ('MARCENARIA', 'Marcenaria'), ('PINTURA', 'Pintura'), ('PAPEIS_EXPEDIENTE', 'Papéis de Expediente'), ('PAPEIS_LIMPEZA', 'Papéis de Limpeza'), ('REFRIGERACAO', 'Refrigeração'), ('TONER', 'Toner')], null=True, verbose_name='Grupo'),
        ),
        migrations.AlterModelOptions(
            name='movimentacoesconsumo',
            options={'verbose_name': 'Movimentação Consumo', 'verbose_name_plural': 'Movimentações de Bens Consumo'},
        ),
        migrations.AlterModelOptions(
            name='movimentacoespermanentes',
            options={'verbose_name': 'Movimentação Permanente', 'verbose_name_plural': 'Movimentações de Bens Permanentes'},
        ),
        migrations.AlterField(
            model_name='bensconsumo',
            name='medida',
            field=models.CharField(blank=True, choices=[('METRO', 'Metro'), ('UNIDADE', 'Unidade'), ('QUILOGRAMA', 'Quilograma'), ('LITRO', 'Litro'), ('PACOTE', 'Pacote'), ('CAIXA', 'Caixa')], max_length=20, null=True, verbose_name='Unidade de Medida'),
        ),
        migrations.AlterField(
            model_name='benspermanentes',
            name='estado_de_conservacao',
            field=models.CharField(blank=True, choices=[('BOM', 'Bom'), ('NOVO', 'Novo'), ('PRECARIO', 'Precário'), ('REGULAR', 'Regular'), ('SUCATA', 'Sucata')], max_length=20, null=True, verbose_name='Estado de Conservação'),
        ),
        migrations.AlterField(
            model_name='benspermanentes',
            name='situacao_fisica',
            field=models.CharField(blank=True, choices=[('ANTIECONOMICO', 'Antieconômico'), ('EM_USO', 'Em Uso'), ('IRRECUPERAVEL', 'Irrecuperável'), ('OCIOSO', 'Ocioso'), ('RECUPERAVEL', 'Recuperável')], max_length=20, null=True, verbose_name='Situação Física'),
        ),
        migrations.AlterField(
            model_name='infoua',
            name='contato_ua',
            field=models.CharField(blank=True, max_length=15, null=True, validators=[django.core.validators.RegexValidator(regex='^\\+?\\d{10,15}$')], verbose_name='Contato da UA'),
        ),
        migrations.AddField(
            model_name='bensconsumo',
            name='local',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='localizacao_consumo', to='sipat.localizacao', verbose_name='Localização'),
        ),
        migrations.AddField(
            model_name='localizacao',
            name='setor_sala',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='localizacao_interna', to='sipat.setor', verbose_name='Setor/Sala'),
        ),
        migrations.DeleteModel(
            name='GrupoConsumo',
        ),
    ]
