# Generated by Django 6.0.2 on 2026-02-11 17:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sipat', '0011_localizacao_setor_alter_bensconsumo_grupo_consumo_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Locais',
            new_name='CircunscricaoPredio',
        ),
        migrations.RenameModel(
            old_name='Localizacao',
            new_name='LocalizacaoDEMPAM',
        ),
        migrations.RenameModel(
            old_name='Setor',
            new_name='SetorDEMPAM',
        ),
        migrations.AlterModelOptions(
            name='circunscricaopredio',
            options={'verbose_name': 'Circunscrição/Prédio', 'verbose_name_plural': 'Circunscrições/Prédios'},
        ),
        migrations.AlterModelOptions(
            name='localizacaodempam',
            options={'verbose_name': 'Localização DEMPAM', 'verbose_name_plural': 'Localizações DEMPAM'},
        ),
        migrations.RenameField(
            model_name='bensconsumo',
            old_name='local',
            new_name='local_armazenamento',
        ),
    ]
