# Generated by Django 6.0.2 on 2026-02-11 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sipat', '0012_rename_locais_circunscricaopredio_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='movimentacoesconsumo',
            options={'verbose_name': 'Movimentação (Consumo)', 'verbose_name_plural': 'Movimentações (Consumo)'},
        ),
        migrations.AlterModelOptions(
            name='movimentacoespermanentes',
            options={'verbose_name': 'Movimentação (Permanente)', 'verbose_name_plural': 'Movimentações (Permanentes)'},
        ),
        migrations.AlterModelOptions(
            name='setordempam',
            options={'verbose_name': 'Setor/Sala DEMPAM', 'verbose_name_plural': 'Setores/Salas DEMPAM'},
        ),
        migrations.AlterField(
            model_name='localizacaodempam',
            name='tipo_localizacao',
            field=models.CharField(blank=True, choices=[('PALLET', 'Pallet'), ('PRATELEIRA', 'Prateleira')], max_length=30, null=True),
        ),
    ]
