# Generated by Django 6.0.2 on 2026-02-19 20:41

import django.core.validators
import django.db.models.deletion
import localflavor.br.models
import sipat.utils
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sipat', '0013_alter_movimentacoesconsumo_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BensEnviados',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Fornecedor',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('fornecedor', models.CharField(max_length=40, verbose_name='Fornecedor')),
                ('cnpj_fornecedor', localflavor.br.models.BRCNPJField(blank=True, max_length=18, null=True, verbose_name='CNPJ do Fornecedor')),
                ('contato_fornecedor', models.CharField(blank=True, max_length=15, null=True, validators=[django.core.validators.RegexValidator(regex='^\\+?\\d{10,15}$')], verbose_name='Contato do Fornecedor')),
                ('email_fornecedor', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email do Fornecedor')),
            ],
            options={
                'verbose_name': 'Fornecedor',
                'verbose_name_plural': 'Fonecedores',
            },
        ),
        migrations.CreateModel(
            name='SolicitacoesSalvoAtivo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Tramitacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.RemoveField(
            model_name='bensconsumo',
            name='custo_unit',
        ),
        migrations.RemoveField(
            model_name='bensconsumo',
            name='imagem_consumo',
        ),
        migrations.RemoveField(
            model_name='bensconsumo',
            name='local_armazenamento',
        ),
        migrations.RemoveField(
            model_name='bensconsumo',
            name='marca',
        ),
        migrations.RemoveField(
            model_name='bensconsumo',
            name='quantidade',
        ),
        migrations.RemoveField(
            model_name='bensconsumo',
            name='validade',
        ),
        migrations.AddField(
            model_name='bensconsumo',
            name='descricao_efisco',
            field=models.TextField(blank=True, null=True, verbose_name='Descrição Efisco'),
        ),
        migrations.AddField(
            model_name='bensconsumo',
            name='descricao_manual',
            field=models.CharField(blank=True, max_length=60, null=True, verbose_name='Descrição Manual'),
        ),
        migrations.CreateModel(
            name='BensConsumoEstoque',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('quantidade', models.PositiveIntegerField(verbose_name='Quantidade')),
                ('local_armazenamento', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='localizacao_consumo', to='sipat.localizacaodempam', verbose_name='Localização')),
                ('solicitacao', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='estoquesolicitacao', to='sipat.bensenviados', verbose_name='Estoque da Solicitação')),
            ],
            options={
                'verbose_name': 'Bem de Consumo',
                'verbose_name_plural': 'Bens de Consumo',
            },
        ),
        migrations.CreateModel(
            name='CompraIndividual',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bem', models.CharField(blank=True, max_length=50, null=True, verbose_name='Bem')),
                ('quantidade', models.PositiveIntegerField(blank=True, null=True, verbose_name='Quantidade')),
                ('valor', models.PositiveIntegerField(verbose_name='Valor')),
                ('nf', models.FileField(blank=True, null=True, upload_to=sipat.utils.caminho_nf_compraindividual, verbose_name='Nota Fiscal')),
                ('data_compra', models.DateField(blank=True, null=True, verbose_name='Data da Compra')),
                ('efisco', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='compras_individuais', to='sipat.bensconsumo', verbose_name='Efisco')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='usuario_compraindividual', to=settings.AUTH_USER_MODEL, verbose_name='Usuário Responsável')),
            ],
        ),
        migrations.CreateModel(
            name='Contrato',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('contrato', models.CharField(max_length=30, verbose_name='N° Contrato')),
                ('inicio_vigencia', models.DateField(blank=True, null=True, verbose_name='Início da Vigência')),
                ('final_vigencia', models.DateField(blank=True, null=True, verbose_name='Final da Vigência')),
                ('homologacao', models.DateField(blank=True, null=True, verbose_name='Homologação')),
                ('cs', models.IntegerField(blank=True, null=True, verbose_name='N° CS')),
                ('cod_liquidacao', models.IntegerField(blank=True, null=True, verbose_name='Código de Licitação')),
                ('fornecedor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='sipat.fornecedor')),
            ],
            options={
                'verbose_name': 'Contrato',
                'verbose_name_plural': 'Contratos',
            },
        ),
        migrations.CreateModel(
            name='SaldoAtivo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('quantidade_contrato', models.PositiveIntegerField(verbose_name='Quantidade Contrato')),
                ('saldo_disponivel', models.PositiveIntegerField(editable=False, verbose_name='Saldo Disponível')),
                ('cota', models.CharField(blank=True, choices=[('PRINCIPAL', 'Principal'), ('RESERVADA', 'Reservada')], max_length=15, null=True, verbose_name='Cota')),
                ('contrato_saldo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='Contrato', to='sipat.contrato', verbose_name='Contrato')),
                ('efisco', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='saldos_ativos', to='sipat.bensconsumo', verbose_name='Efisco')),
            ],
            options={
                'verbose_name': 'Saldo Ativo',
                'verbose_name_plural': 'Saldo Ativo',
                'unique_together': {('contrato_saldo', 'efisco')},
            },
        ),
        migrations.CreateModel(
            name='SolicitacoesConsumo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('quantidade', models.PositiveIntegerField(verbose_name='Quantidade')),
                ('data_hora', models.DateTimeField(auto_now_add=True, verbose_name='Data e Hora da Movimentação')),
                ('observacao', models.TextField(blank=True, null=True, verbose_name='Observação')),
                ('anexo', models.FileField(blank=True, null=True, upload_to=sipat.utils.caminho_movimentacao_consumo, verbose_name='Documento Anexado')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='itens_movimentados', to='sipat.bensconsumo', verbose_name='Item Movimentado')),
                ('solicitante', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='solicitantesconsumo', to='sipat.infoua', verbose_name='Solicitante')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='usuario_sol_consumo', to=settings.AUTH_USER_MODEL, verbose_name='Usuário Responsável')),
            ],
            options={
                'verbose_name': 'Movimentação (Consumo)',
                'verbose_name_plural': 'Movimentações (Consumo)',
            },
        ),
        migrations.DeleteModel(
            name='MovimentacoesConsumo',
        ),
    ]
