# Generated by Django 6.0.2 on 2026-02-19 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sipat', '0014_bensenviados_fornecedor_solicitacoessalvoativo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='saldoativo',
            name='saldo_disponivel',
            field=models.PositiveIntegerField(default=0, editable=False, verbose_name='Saldo Disponível'),
        ),
    ]
