# Generated by Django 6.0.2 on 2026-02-19 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sipat', '0015_alter_saldoativo_saldo_disponivel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='saldoativo',
            name='saldo_disponivel',
            field=models.PositiveIntegerField(default=0, verbose_name='Saldo Disponível'),
        ),
    ]
