# Generated by Django 6.0.2 on 2026-02-20 14:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sipat', '0016_alter_saldoativo_saldo_disponivel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='benspermanentes',
            name='cpf_fornecedor',
        ),
    ]
