# Generated by Django 6.0.2 on 2026-02-20 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sipat', '0017_remove_benspermanentes_cpf_fornecedor'),
    ]

    operations = [
        migrations.AddField(
            model_name='contrato',
            name='status',
            field=models.CharField(choices=[('ABERTO', 'Aberto'), ('FECHADO', 'Fechado')], default='Aberto', max_length=10),
        ),
        migrations.AlterField(
            model_name='saldoativo',
            name='saldo_disponivel',
            field=models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='Saldo Disponível'),
        ),
    ]
