# Generated by Django 6.0.2 on 2026-02-20 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sipat', '0018_contrato_status_alter_saldoativo_saldo_disponivel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contrato',
            name='status',
        ),
        migrations.AlterField(
            model_name='saldoativo',
            name='saldo_disponivel',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Saldo Disponível'),
        ),
    ]
