# Generated by Django 6.0.2 on 2026-02-20 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sipat', '0019_remove_contrato_status_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bensconsumo',
            name='descricao_manual',
        ),
        migrations.AddField(
            model_name='saldoativo',
            name='descricao_manual',
            field=models.CharField(blank=True, max_length=60, null=True, verbose_name='Descrição Manual'),
        ),
        migrations.AddField(
            model_name='saldoativo',
            name='marca',
            field=models.CharField(blank=True, max_length=60, null=True, verbose_name='Marca'),
        ),
    ]
