# Generated by Django 6.0.2 on 2026-02-23 17:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sipat', '0020_remove_bensconsumo_descricao_manual_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SolicitacoesSaldoAtivo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('codigo', models.CharField(editable=False, max_length=30, unique=True, verbose_name='Código da Solicitação')),
                ('status', models.CharField(choices=[('RASCUNHO', 'Rascunho'), ('ENVIADA', 'Enviada'), ('ATENDIDA', 'Atendida'), ('CANCELADA', 'Cancelada')], default='Rascunho', max_length=20, verbose_name='Status')),
                ('data_hora', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Data e Hora da Movimentação')),
                ('contrato', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='contrato_soli_saldoativo', to='sipat.contrato', verbose_name='Contrato')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='usuario_solic_saldoativo', to=settings.AUTH_USER_MODEL, verbose_name='Usuário Responsável')),
            ],
            options={
                'verbose_name': 'Solicitação Saldo Ativo',
                'verbose_name_plural': 'Solicitação Saldo Ativo',
            },
        ),
        migrations.DeleteModel(
            name='SolicitacoesSalvoAtivo',
        ),
        migrations.AddField(
            model_name='bensenviados',
            name='bem',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='itens_enviados', to='sipat.saldoativo', verbose_name='Item do Contrato (Saldo Ativo)'),
        ),
        migrations.AddField(
            model_name='bensenviados',
            name='quantidade',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Quantidade Solicitada'),
        ),
        migrations.AlterField(
            model_name='bensenviados',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='bensenviados',
            name='solicitacao',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bensenviados_saldoativo', to='sipat.solicitacoessaldoativo', verbose_name='Solicitação'),
        ),
        migrations.AddConstraint(
            model_name='bensenviados',
            constraint=models.UniqueConstraint(fields=('solicitacao', 'bem'), name='uniq_item_por_solicitacao'),
        ),
    ]
