# Generated by Django 6.0.2 on 2026-02-23 18:45

import dimrcbp.utils
import django.core.validators
import django.db.models.deletion
import localflavor.br.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('dempam', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BensPermanentes',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('descricao', models.CharField(blank=True, default='Não Consta', editable=False, max_length=100, verbose_name='Descrição')),
                ('forma_de_controle', models.CharField(default='Individual', editable=False, max_length=15, verbose_name='Forma de Controle')),
                ('tipo_de_bem', models.CharField(default='Móvel', editable=False, max_length=15, verbose_name='Tipo do Bem')),
                ('imobilizado', models.BooleanField(default=True, editable=False, verbose_name='Imobilizado')),
                ('marca_fabricante', models.CharField(blank=True, default='Sem Marca', max_length=60, verbose_name='Marca/Fabricante')),
                ('modelo', models.CharField(blank=True, default='S/Modelo', max_length=60, verbose_name='Modelo')),
                ('numero_de_serie', models.CharField(blank=True, default='S/Número', max_length=30, verbose_name='Número de Série')),
                ('situacao_juridica', models.CharField(default='Regular', editable=False, max_length=15, verbose_name='Situação Jurídica')),
                ('situacao_fisica', models.CharField(blank=True, choices=[('ANTIECONOMICO', 'Antieconômico'), ('EM_USO', 'Em Uso'), ('IRRECUPERAVEL', 'Irrecuperável'), ('OCIOSO', 'Ocioso'), ('RECUPERAVEL', 'Recuperável')], max_length=20, null=True, verbose_name='Situação Física')),
                ('estado_de_conservacao', models.CharField(blank=True, choices=[('BOM', 'Bom'), ('NOVO', 'Novo'), ('PRECARIO', 'Precário'), ('REGULAR', 'Regular'), ('SUCATA', 'Sucata')], max_length=20, null=True, verbose_name='Estado de Conservação')),
                ('forma_de_ingresso', models.CharField(blank=True, default='Compra', editable=False, max_length=15, verbose_name='Forma de Ingresso')),
                ('nota_fiscal', models.CharField(blank=True, default='S/Nota Fiscal', max_length=20, verbose_name='Nota Fiscal')),
                ('tipo_do_documento', models.CharField(blank=True, default='Nota Fiscal', editable=False, max_length=20, verbose_name='Tipo do Documento')),
                ('codigo_unidade', models.CharField(blank=True, default='320101', editable=False, max_length=10, verbose_name='Código da Unidade')),
                ('cnpj_fornecedor', localflavor.br.models.BRCNPJField(blank=True, max_length=18, null=True, verbose_name='CNPJ do Fornecedor')),
                ('data_aquisicao', models.DateField(blank=True, null=True, verbose_name='Data da aquisição')),
                ('modalidade', models.CharField(blank=True, default='Pregão Eletrônico', editable=False, max_length=25, verbose_name='Modalidade')),
                ('numero_do_processo', models.CharField(blank=True, default='S/Número', max_length=20, verbose_name='Número do Processo')),
                ('codigo_natureza_de_despesa', models.CharField(blank=True, default='S/Número', max_length=20, verbose_name='Código Natureza de Despesa')),
                ('moeda', models.CharField(default='REAL', editable=False, max_length=5, verbose_name='Moeda')),
                ('numero_da_af', models.CharField(blank=True, default='S/Número', max_length=20, verbose_name='Número da AF')),
                ('numero_do_empenho', models.CharField(blank=True, default='S/Número', max_length=20, verbose_name='Número do Empenho')),
                ('garantia_em_dias', models.DateField(blank=True, null=True, verbose_name='Vencimento Garantia')),
                ('valor_unitario', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=12, null=True, verbose_name='Valor Unitário')),
                ('qtde', models.IntegerField(blank=True, verbose_name='Quantidade')),
                ('observacao', models.TextField(blank=True, default='', max_length=80, verbose_name='Observação')),
                ('conta_contabil', models.CharField(blank=True, default='Ativo Móveis', max_length=20, verbose_name='Conta Contábil')),
                ('tombamento_legado', models.IntegerField(blank=True, null=True, unique=True, verbose_name='Tombo')),
                ('valor_atual_do_bem', models.DecimalField(blank=True, decimal_places=2, default=0, editable=False, max_digits=12, verbose_name='Valor Atual do Bem')),
                ('descricao_manual', models.CharField(blank=True, max_length=30, null=True, verbose_name='Descrição Manual')),
                ('classe', models.CharField(blank=True, max_length=30, null=True, verbose_name='Classe')),
                ('subclasse', models.CharField(blank=True, max_length=30, null=True, verbose_name='Subclasse')),
                ('subclasse_2', models.CharField(blank=True, max_length=30, null=True, verbose_name='Subclasse 2')),
                ('subclasse_3', models.CharField(blank=True, max_length=30, null=True, verbose_name='Subclasse 3')),
                ('venc_garantia', models.DateField(blank=True, null=True, verbose_name='Vencimento da Garantia')),
                ('imagem_permanente', models.ImageField(blank=True, null=True, upload_to=dimrcbp.utils.caminho_benspermanentes, verbose_name='Imagem do Bem')),
                ('nome_resp_uso_ext', models.CharField(blank=True, default='Não Consta', max_length=50, verbose_name='Nome Responsável Uso Externo')),
                ('matricula_resp_uso_ext', models.CharField(blank=True, default='Não Consta', max_length=25, null=True, verbose_name='Matrícula Responsável Uso Externo')),
                ('contato_resp_uso_ext', models.CharField(blank=True, max_length=16, null=True, validators=[django.core.validators.RegexValidator(regex='^\\+?\\d{10,15}$')], verbose_name='Contato Responsável Uso Externo')),
                ('ua_atual', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='uas_com_bens_cadastrados', to='dempam.infoua', verbose_name='UA Atual')),
                ('unidade_gestora', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='unidades_gestora_dos_bens', to='dempam.infoua', verbose_name='Unidade Gestora')),
            ],
            options={
                'verbose_name': 'Bem Permanente',
                'verbose_name_plural': 'Bens Permanentes',
            },
        ),
        migrations.CreateModel(
            name='MovimentacoesPermanentes',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('sei', models.CharField(blank=True, max_length=25, null=True, verbose_name='SEI')),
                ('acao', models.CharField(choices=[('SOLICITACAO', 'Solicitação'), ('DEVOLUCAO', 'Devolução'), ('TRANSFERENCIA', 'Transferência')], default='TRANSFERENCIA', verbose_name='Ação')),
                ('data_hora', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Data e Hora da Movimentação')),
                ('anexo', models.FileField(blank=True, null=True, upload_to=dimrcbp.utils.caminho_benspermanentes, verbose_name='Documento Anexado')),
                ('nome_resp_uso_ext', models.CharField(blank=True, default='Não Consta', max_length=50, verbose_name='Nome Responsável Uso Externo')),
                ('matricula_resp_uso_ext', models.CharField(blank=True, default='Não Consta', max_length=25, null=True, verbose_name='Matrícula Responsável Uso Externo')),
                ('contato_resp_uso_ext', models.CharField(blank=True, max_length=25, null=True, validators=[django.core.validators.RegexValidator(regex='^\\+?\\d{10,15}$')], verbose_name='Contato Responsável Uso Externo')),
                ('destino', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='destinos_uas', to='dempam.infoua', verbose_name='Destino')),
                ('origem', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='origens_uas', to='dempam.infoua', verbose_name='Origem')),
                ('tombo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='tombos_movimentados', to='dimrcbp.benspermanentes', verbose_name='Tombo')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='usuario_mov_permanentes', to=settings.AUTH_USER_MODEL, verbose_name='Usuário Responsável')),
            ],
            options={
                'verbose_name': 'Movimentação (Permanente)',
                'verbose_name_plural': 'Movimentações (Permanentes)',
            },
        ),
    ]
