# Generated by Django 6.0.2 on 2026-04-20 17:38

import dimrcbp.utils
import django.core.validators
import django.db.models.deletion
import localflavor.br.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('dempam', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BensPermanentes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tombo', models.CharField(max_length=20, unique=True, verbose_name='Tombo')),
                ('description', models.TextField(verbose_name='Descrição')),
                ('mark', models.CharField(max_length=60, verbose_name='Marca/Fabricante')),
                ('model', models.CharField(max_length=60, verbose_name='Modelo')),
                ('n_series', models.CharField(max_length=30, verbose_name='Número de Série')),
                ('acquisition_date', models.DateField(verbose_name='Data da Aquisição')),
                ('value', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Valor Unitário')),
                ('photo', models.ImageField(blank=True, null=True, upload_to=dimrcbp.utils.caminho_benspermanentes, verbose_name='Imagem do Bem')),
                ('state', models.CharField(blank=True, choices=[('BOM', 'Bom'), ('NOVO', 'Novo'), ('PRECARIO', 'Precário'), ('REGULAR', 'Regular'), ('SUCATA', 'Sucata')], max_length=20, null=True, verbose_name='Estado de Conservação')),
                ('situacion', models.CharField(blank=True, choices=[('ANTIECONOMICO', 'Antieconômico'), ('EM_USO', 'Em Uso'), ('IRRECUPERAVEL', 'Irrecuperável'), ('OCIOSO', 'Ocioso'), ('RECUPERAVEL', 'Recuperável')], max_length=20, null=True, verbose_name='Situação Física')),
                ('entry_method', models.CharField(blank=True, default='Compra', max_length=15, verbose_name='Forma de Ingresso')),
                ('n_empenho', models.CharField(blank=True, default='S/Número', max_length=20, verbose_name='Número do Empenho')),
                ('n_process', models.CharField(blank=True, default='S/Número', max_length=20, verbose_name='Número do Processo')),
                ('modality', models.CharField(blank=True, default='Pregão Eletrônico', max_length=25, verbose_name='Modalidade')),
                ('supllier', localflavor.br.models.BRCNPJField(blank=True, max_length=18, null=True, verbose_name='Fornecedor')),
            ],
            options={
                'verbose_name': 'Bem Permanente',
                'verbose_name_plural': 'Bens Permanentes',
            },
        ),
        migrations.CreateModel(
            name='Groups',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group', models.CharField(max_length=30, unique=True, verbose_name='Nome do Grupo')),
            ],
            options={
                'verbose_name': 'Grupo',
                'verbose_name_plural': 'Grupos',
            },
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nome do Fornecedor')),
                ('cnpj', localflavor.br.models.BRCNPJField(max_length=18, unique=True, verbose_name='CNPJ do Fornecedor')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email do Fornecedor')),
                ('phone', models.CharField(blank=True, max_length=16, null=True, validators=[django.core.validators.RegexValidator(regex='^\\+?\\d{10,15}$')], verbose_name='Telefone do Fornecedor')),
                ('Responsible', models.CharField(blank=True, max_length=50, null=True, verbose_name='Responsável pelo Fornececimento')),
            ],
            options={
                'verbose_name': 'Fornecedor',
                'verbose_name_plural': 'Fornecedores',
            },
        ),
        migrations.CreateModel(
            name='HistoryUas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_year', models.IntegerField(blank=True, verbose_name='Ano Entrada Ua Atual')),
                ('current_responsible', models.CharField(blank=True, max_length=50, verbose_name='Responsável da Ua Atual')),
                ('current_registration', models.CharField(blank=True, max_length=50, verbose_name='Matrícula do Responsável da Ua Atual')),
                ('last_year', models.IntegerField(blank=True, verbose_name='Ano Entrada Ua Anterior')),
                ('last_responsible', models.CharField(blank=True, max_length=50, verbose_name='Responsável da última Ua')),
                ('last_registration', models.CharField(blank=True, max_length=50, verbose_name='Matrícula do Responsável da Ua Anterior')),
                ('penultimate_year', models.IntegerField(blank=True, verbose_name='Ano Entrada Ua Penúltima')),
                ('penultimate_responsible', models.CharField(blank=True, max_length=50, verbose_name='Responsável da penúltima')),
                ('penultimate_registration', models.CharField(blank=True, max_length=50, verbose_name='Matrícula do Responsável da Ua penúltima')),
                ('third_last_year', models.IntegerField(blank=True, verbose_name='Ano Entrada Ua Antepenúltima')),
                ('current_ua', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='history_current_ua', to='dempam.infoua', verbose_name='UA Atual')),
                ('last_ua', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='history_last_ua', to='dempam.infoua', verbose_name='UA Anterior')),
                ('penultimate_ua', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='history_penultimate_ua', to='dempam.infoua', verbose_name='UA Penúltima')),
                ('third_last_ua', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='history_third_last_ua', to='dempam.infoua', verbose_name='UA Antepenúltima')),
                ('tombo', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='history_tombo', to='dempam.infoua', verbose_name='Tombo')),
            ],
            options={
                'verbose_name': 'Histórico das Uas',
                'verbose_name_plural': 'Histórico das Uas',
            },
        ),
        migrations.CreateModel(
            name='Type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=30, unique=True, verbose_name='Nome do Tipo')),
                ('gruop', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='dimrcbp.groups', verbose_name='Grupo')),
            ],
            options={
                'verbose_name': 'Tipo',
                'verbose_name_plural': 'Tipos',
            },
        ),
        migrations.CreateModel(
            name='Description',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(verbose_name='Descrição')),
                ('classification', models.CharField(blank=True, max_length=30, verbose_name='Classificação')),
                ('subclassification', models.CharField(blank=True, max_length=30, verbose_name='Subclassificação')),
                ('btu_hp', models.IntegerField(blank=True, verbose_name='BTU/HP')),
                ('size', models.CharField(blank=True, max_length=30, verbose_name='Tamanho')),
                ('color', models.CharField(blank=True, choices=[('BRANCO', 'Branco'), ('PRETO', 'Preto'), ('CINZA', 'Cinza'), ('VERMELHO', 'Vermelho'), ('AZUL', 'Azul'), ('VERDE', 'Verde'), ('AMARELO', 'Amarelo'), ('LARANJA', 'Laranja'), ('ROXO', 'Roxo'), ('ROSA', 'Rosa'), ('MARROM', 'Marrom'), ('AZUL_CLARO', 'Azul claro'), ('AZUL_ESCURO', 'Azul escuro'), ('VERDE_CLARO', 'Verde claro'), ('VERDE_ESCURO', 'Verde escuro'), ('VERMELHO_ESCURO', 'Vermelho escuro'), ('AMARELO_CLARO', 'Amarelo claro'), ('CINZA_CLARO', 'Cinza claro'), ('CINZA_ESCURO', 'Cinza escuro'), ('BEGE', 'Bege'), ('CREME', 'Creme'), ('VINHO', 'Vinho'), ('BORDO', 'Bordô'), ('TURQUESA', 'Turquesa'), ('LILAS', 'Lilás'), ('SALMAO', 'Salmão'), ('DOURADO', 'Dourado'), ('PRATEADO', 'Prateado'), ('BRANCO_GELO', 'Branco gelo'), ('BRANCO_FOSCO', 'Branco fosco'), ('BRANCO_BRILHANTE', 'Branco brilhante'), ('PRETO_FOSCO', 'Preto fosco'), ('PRETO_BRILHANTE', 'Preto brilhante'), ('GRAFITE', 'Grafite'), ('INOX', 'Inox'), ('CROMADO', 'Cromado'), ('AMADEIRADO', 'Amadeirado'), ('CARVALHO', 'Carvalho'), ('IMBUIA', 'Imbuia'), ('MOGNO', 'Mogno'), ('NOGUEIRA', 'Nogueira')], max_length=40, verbose_name='Cor')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='dimrcbp.type', verbose_name='Tipo')),
            ],
            options={
                'verbose_name': 'Descrição',
                'verbose_name_plural': 'Descrições',
            },
        ),
        migrations.CreateModel(
            name='UseExternal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('responsible', models.CharField(max_length=50, verbose_name='Responsável pelo Uso Externo')),
                ('contact_responsible', models.CharField(blank=True, max_length=16, validators=[django.core.validators.RegexValidator(regex='^\\+?\\d{10,15}$')], verbose_name='Contato do Uso Externo')),
                ('registration_responsible', models.CharField(max_length=50, verbose_name='Registro do Responsável pelo Uso Externo')),
                ('email_responsible', models.EmailField(blank=True, max_length=254, verbose_name='Email do Uso Externo')),
                ('user', models.CharField(blank=True, max_length=50, verbose_name='Usuário do Uso Externo')),
                ('cpf_user', models.CharField(blank=True, max_length=14, verbose_name='CPF do Usuário do Uso Externo')),
                ('email_user', models.EmailField(blank=True, max_length=254, verbose_name='Email do Usuário do Uso Externo')),
                ('phone_user', models.CharField(blank=True, max_length=16, validators=[django.core.validators.RegexValidator(regex='^\\+?\\d{10,15}$')], verbose_name='Telefone do Usuário do Uso Externo')),
                ('date_renovation', models.DateField(verbose_name='Data de Renovação do Uso Externo')),
                ('tombo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='dimrcbp.benspermanentes', verbose_name='Tombo')),
            ],
            options={
                'verbose_name': 'Uso Externo',
                'verbose_name_plural': 'Usos Externos',
            },
        ),
    ]
