# Generated by Django 6.0.2 on 2026-04-20 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dimrcbp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='description',
            name='btu_hp',
            field=models.IntegerField(blank=True, null=True, verbose_name='BTU/HP'),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='cnpj',
            field=models.CharField(max_length=22, unique=True, verbose_name='CNPJ do Fornecedor'),
        ),
    ]
