# Generated by Django 6.0.2 on 2026-02-23 20:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dimrcbp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='benspermanentes',
            options={'verbose_name': 'Bem Permanente', 'verbose_name_plural': '01 - Bens Permanentes'},
        ),
        migrations.AlterModelOptions(
            name='movimentacoespermanentes',
            options={'verbose_name': 'Movimentação (Permanente)', 'verbose_name_plural': '02 - Movimentações (Permanentes)'},
        ),
    ]
