# Generated by Django 6.0.2 on 2026-04-20 18:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dimrcbp', '0002_alter_description_btu_hp_alter_supplier_cnpj'),
    ]

    operations = [
        migrations.AlterField(
            model_name='benspermanentes',
            name='description',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='description_tombo', to='dimrcbp.description', verbose_name='Descrição'),
        ),
        migrations.AlterField(
            model_name='benspermanentes',
            name='supllier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='dimrcbp.supplier', verbose_name='Fornecedor'),
        ),
    ]
