# Generated by Django 6.0.2 on 2026-03-02 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dimrcbp', '0002_alter_benspermanentes_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='movimentacoespermanentes',
            name='codigo',
            field=models.CharField(default=2, editable=False, max_length=30, unique=True, verbose_name='Código da Movimentação'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='benspermanentes',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='movimentacoespermanentes',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
