# Generated by Django 6.0.2 on 2026-04-20 18:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dimrcbp', '0003_alter_benspermanentes_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historyuas',
            name='current_registration',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Matrícula do Responsável da Ua Atual'),
        ),
        migrations.AlterField(
            model_name='historyuas',
            name='current_responsible',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Responsável da Ua Atual'),
        ),
        migrations.AlterField(
            model_name='historyuas',
            name='current_year',
            field=models.IntegerField(blank=True, null=True, verbose_name='Ano Entrada Ua Atual'),
        ),
        migrations.AlterField(
            model_name='historyuas',
            name='last_registration',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Matrícula do Responsável da Ua Anterior'),
        ),
        migrations.AlterField(
            model_name='historyuas',
            name='last_responsible',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Responsável da última Ua'),
        ),
        migrations.AlterField(
            model_name='historyuas',
            name='last_year',
            field=models.IntegerField(blank=True, null=True, verbose_name='Ano Entrada Ua Anterior'),
        ),
        migrations.AlterField(
            model_name='historyuas',
            name='penultimate_registration',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Matrícula do Responsável da Ua penúltima'),
        ),
        migrations.AlterField(
            model_name='historyuas',
            name='penultimate_responsible',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Responsável da penúltima'),
        ),
        migrations.AlterField(
            model_name='historyuas',
            name='penultimate_year',
            field=models.IntegerField(blank=True, null=True, verbose_name='Ano Entrada Ua Penúltima'),
        ),
        migrations.AlterField(
            model_name='historyuas',
            name='third_last_year',
            field=models.IntegerField(blank=True, null=True, verbose_name='Ano Entrada Ua Antepenúltima'),
        ),
        migrations.AlterField(
            model_name='historyuas',
            name='tombo',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='history_tombo', to='dimrcbp.benspermanentes', verbose_name='Tombo'),
        ),
    ]
