# Generated by Django 6.0.2 on 2026-04-28 16:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dimrcbp', '0004_alter_historyuas_current_registration_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PeriodoInventario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=100, verbose_name='Descrição')),
                ('inicio', models.DateField(verbose_name='Início')),
                ('fim', models.DateField(verbose_name='Fim')),
            ],
            options={
                'verbose_name': 'Período de Inventário',
                'verbose_name_plural': '8 - Períodos de Inventário',
                'ordering': ['-inicio'],
            },
        ),
        migrations.AlterModelOptions(
            name='benspermanentes',
            options={'verbose_name': 'Bem Permanente', 'verbose_name_plural': '1 - Bens Permanentes'},
        ),
        migrations.AlterModelOptions(
            name='description',
            options={'verbose_name': 'Descrição', 'verbose_name_plural': '4 - Descrições'},
        ),
        migrations.AlterModelOptions(
            name='groups',
            options={'verbose_name': 'Grupo', 'verbose_name_plural': '2 - Grupos'},
        ),
        migrations.AlterModelOptions(
            name='historyuas',
            options={'verbose_name': 'Histórico das Uas', 'verbose_name_plural': '5 - Histórico das Uas'},
        ),
        migrations.AlterModelOptions(
            name='supplier',
            options={'verbose_name': 'Fornecedor', 'verbose_name_plural': '4 - Fornecedores'},
        ),
        migrations.AlterModelOptions(
            name='type',
            options={'verbose_name': 'Tipo', 'verbose_name_plural': '3 - Tipos'},
        ),
        migrations.AlterModelOptions(
            name='useexternal',
            options={'verbose_name': 'Uso Externo', 'verbose_name_plural': '6 - Usos Externos'},
        ),
        migrations.RemoveField(
            model_name='description',
            name='btu_hp',
        ),
        migrations.AddField(
            model_name='description',
            name='capacity',
            field=models.IntegerField(blank=True, null=True, verbose_name='BTU/HP'),
        ),
        migrations.AddField(
            model_name='description',
            name='subdescription',
            field=models.CharField(blank=True, max_length=30, verbose_name='Subdescrição'),
        ),
        migrations.CreateModel(
            name='AtribuicaoBem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('desde', models.DateField(auto_now_add=True, verbose_name='Atribuído desde')),
                ('ativo', models.BooleanField(default=True, verbose_name='Atribuição ativa')),
                ('bem', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='atribuicoes', to='dimrcbp.benspermanentes', verbose_name='Bem Permanente')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bens_atribuidos', to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
            ],
            options={
                'verbose_name': 'Atribuição de Bem',
                'verbose_name_plural': '7 - Atribuições de Bens',
            },
        ),
    ]
