# Generated by Django 6.0.2 on 2026-04-20 16:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dempam', '0001_initial'),
        ('dimrcbp', '0004_alter_historyuas_current_registration_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MovimentacoesPermanentes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sei', models.CharField(blank=True, max_length=25, null=True, verbose_name='SEI')),
                ('acao', models.CharField(choices=[('SOLICITACAO', 'Solicitação'), ('DEVOLUCAO', 'Devolução'), ('TRANSFERENCIA', 'Transferência')], max_length=20, verbose_name='Ação')),
                ('data_hora', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Data e Hora')),
                ('anexo', models.FileField(blank=True, null=True, upload_to='bens/movimentacoes/', verbose_name='Anexo')),
                ('nome_resp_uso_ext', models.CharField(blank=True, max_length=50, verbose_name='Responsável pelo Uso Externo')),
                ('matricula_resp_uso_ext', models.CharField(blank=True, max_length=25, null=True, verbose_name='Matrícula do Responsável')),
                ('contato_resp_uso_ext', models.CharField(blank=True, max_length=25, null=True, verbose_name='Contato do Responsável')),
                ('codigo', models.CharField(blank=True, max_length=30, verbose_name='Código')),
                ('destino', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='movimentacoes_destino', to='dempam.infoua', verbose_name='Destino')),
                ('origem', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='movimentacoes_origem', to='dempam.infoua', verbose_name='Origem')),
                ('tombo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='dimrcbp.benspermanentes', verbose_name='Tombo')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
            ],
            options={
                'verbose_name': 'Movimentação Permanente',
                'verbose_name_plural': 'Movimentações Permanentes',
            },
        ),
    ]
