# Generated by Django 6.0.2 on 2026-05-04 12:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dimrcbp', '0005_periodoinventario_alter_benspermanentes_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SolicitacaoMudanca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateTimeField(auto_now_add=True, verbose_name='Data da Solicitação')),
                ('justificativa', models.TextField(verbose_name='Justificativa')),
                ('campos', models.JSONField(verbose_name='Campos Alterados')),
                ('status', models.CharField(choices=[('PENDENTE', 'Pendente'), ('APROVADA', 'Aprovada'), ('REJEITADA', 'Rejeitada')], default='PENDENTE', max_length=10, verbose_name='Status')),
                ('data_decisao', models.DateTimeField(blank=True, null=True, verbose_name='Data da Decisão')),
                ('obs_decisao', models.TextField(blank=True, verbose_name='Observação da Decisão')),
                ('bem', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='solicitacoes_mudanca', to='dimrcbp.benspermanentes', verbose_name='Bem')),
                ('decidido_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='decisoes_mudanca', to=settings.AUTH_USER_MODEL, verbose_name='Decidido por')),
                ('solicitante', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='solicitacoes_mudanca', to=settings.AUTH_USER_MODEL, verbose_name='Solicitante')),
            ],
            options={
                'verbose_name': 'Solicitação de Mudança',
                'verbose_name_plural': '9 - Solicitações de Mudança',
                'ordering': ['-data'],
            },
        ),
    ]
