# Generated by Django 6.0.2 on 2026-05-04 12:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dimrcbp', '0006_solicitacao_mudanca'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricoMudanca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateTimeField(auto_now_add=True, verbose_name='Data da Alteração')),
                ('campos', models.JSONField(verbose_name='Campos Alterados')),
                ('alterado_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='mudancas_realizadas', to=settings.AUTH_USER_MODEL, verbose_name='Alterado por')),
                ('bem', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='historico_mudancas', to='dimrcbp.benspermanentes', verbose_name='Bem')),
            ],
            options={
                'verbose_name': 'Histórico de Mudança',
                'verbose_name_plural': '9 - Histórico de Mudanças',
                'ordering': ['-data'],
            },
        ),
        migrations.DeleteModel(
            name='SolicitacaoMudanca',
        ),
    ]
