# Generated by Django 6.0.2 on 2026-05-04 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dimrcbp', '0007_historico_mudanca'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicomudanca',
            name='justificativa',
            field=models.TextField(blank=True, verbose_name='Justificativa'),
        ),
    ]
