# Generated by Django 6.0.2 on 2026-05-06 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dimrcbp', '0011_catalogo_descricao'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='catalogo',
            options={'ordering': ['description__type__gruop', 'description'], 'verbose_name': 'Catálogo', 'verbose_name_plural': '10 - Catálogos'},
        ),
        migrations.AlterField(
            model_name='catalogo',
            name='value',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True, verbose_name='Valor Unitário de Referência'),
        ),
    ]
