# Generated by Django 6.0.2 on 2026-05-06 12:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dimrcbp', '0012_alter_catalogo_value_max_digits'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PrazoBem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('GARANTIA', 'Garantia'), ('MANUTENCAO', 'Manutenção Preventiva'), ('CALIBRACAO', 'Calibração'), ('SEGURO', 'Seguro'), ('LICENCA', 'Licença / Software'), ('CONTRATO', 'Contrato'), ('OUTRO', 'Outro')], max_length=20, verbose_name='Tipo de Prazo')),
                ('descricao', models.CharField(blank=True, max_length=200, verbose_name='Descrição / Observação')),
                ('data_inicio', models.DateField(blank=True, null=True, verbose_name='Data de Início')),
                ('data_vencimento', models.DateField(verbose_name='Data de Vencimento')),
                ('alertar_dias', models.PositiveIntegerField(default=30, verbose_name='Alertar quantos dias antes')),
                ('renovado', models.BooleanField(default=False, verbose_name='Renovado / Encerrado')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('bem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prazos', to='dimrcbp.benspermanentes', verbose_name='Bem Permanente')),
                ('criado_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='prazos_criados', to=settings.AUTH_USER_MODEL, verbose_name='Registrado por')),
            ],
            options={
                'verbose_name': 'Prazo do Bem',
                'verbose_name_plural': '11 - Prazos dos Bens',
                'ordering': ['data_vencimento'],
            },
        ),
    ]
