# Generated by Django 6.0.2 on 2026-05-06 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dimrcbp', '0013_prazo_bem'),
    ]

    operations = [
        migrations.AddField(
            model_name='benspermanentes',
            name='garantia_vencimento',
            field=models.DateField(blank=True, null=True, verbose_name='Vencimento da Garantia'),
        ),
        migrations.DeleteModel(
            name='PrazoBem',
        ),
    ]
