# Generated by Django 6.0.2 on 2026-05-12 16:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dempam', '0001_initial'),
        ('dimrcbp', '0014_prazos_garantia'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SolicitacaoTransferencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(editable=False, max_length=30, unique=True, verbose_name='Código')),
                ('data', models.DateTimeField(auto_now_add=True, verbose_name='Data da Solicitação')),
                ('motivo', models.TextField(verbose_name='Motivo / Justificativa')),
                ('status', models.CharField(choices=[('PENDENTE', 'Pendente'), ('APROVADA', 'Aprovada'), ('REJEITADA', 'Rejeitada'), ('CANCELADA', 'Cancelada')], default='PENDENTE', max_length=15, verbose_name='Status')),
                ('obs_decisao', models.TextField(blank=True, verbose_name='Observação da Decisão')),
                ('data_decisao', models.DateTimeField(blank=True, null=True, verbose_name='Data da Decisão')),
                ('bem', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='solicitacoes_transferencia', to='dimrcbp.benspermanentes', verbose_name='Bem')),
                ('decidido_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='decisoes_transferencia', to=settings.AUTH_USER_MODEL, verbose_name='Decidido por')),
                ('solicitante', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='solicitacoes_transferencia', to=settings.AUTH_USER_MODEL, verbose_name='Solicitante')),
                ('ua_destino', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='solicitacoes_recebimento', to='dempam.infoua', verbose_name='UA Destino')),
            ],
            options={
                'verbose_name': 'Solicitação de Transferência',
                'verbose_name_plural': '11 - Solicitações de Transferência',
                'ordering': ['-data'],
            },
        ),
        migrations.CreateModel(
            name='MovimentacaoBem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(editable=False, max_length=30, unique=True, verbose_name='Código')),
                ('data', models.DateTimeField(auto_now_add=True, verbose_name='Data da Movimentação')),
                ('motivo', models.TextField(blank=True, verbose_name='Motivo')),
                ('bem', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movimentacoes', to='dimrcbp.benspermanentes', verbose_name='Bem')),
                ('responsavel', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movimentacoes_realizadas', to=settings.AUTH_USER_MODEL, verbose_name='Responsável')),
                ('ua_destino', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='entradas_movimentacao', to='dempam.infoua', verbose_name='UA Destino')),
                ('ua_origem', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='saidas_movimentacao', to='dempam.infoua', verbose_name='UA Origem')),
                ('solicitacao', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='movimentacao', to='dimrcbp.solicitacaotransferencia', verbose_name='Solicitação Origem')),
            ],
            options={
                'verbose_name': 'Movimentação de Bem',
                'verbose_name_plural': '12 - Movimentações de Bens',
                'ordering': ['-data'],
            },
        ),
    ]
