# Generated by Django 6.0.2 on 2026-05-12 16:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dempam', '0001_initial'),
        ('dimrcbp', '0015_solicitacaotransferencia_movimentacaobem'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SolicitacaoCatalogo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(editable=False, max_length=30, unique=True, verbose_name='Código')),
                ('status', models.CharField(choices=[('PENDENTE', 'Pendente'), ('APROVADA', 'Aprovada'), ('REJEITADA', 'Rejeitada'), ('CANCELADA', 'Cancelada')], default='PENDENTE', max_length=15, verbose_name='Status')),
                ('data', models.DateTimeField(auto_now_add=True, verbose_name='Data')),
                ('observacao', models.TextField(blank=True, verbose_name='Observação')),
                ('obs_decisao', models.TextField(blank=True, verbose_name='Obs. Decisão')),
                ('data_decisao', models.DateTimeField(blank=True, null=True, verbose_name='Data Decisão')),
                ('decidido_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='decisoes_catalogo', to=settings.AUTH_USER_MODEL, verbose_name='Decidido por')),
                ('solicitante', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='solicitacoes_catalogo', to=settings.AUTH_USER_MODEL, verbose_name='Solicitante')),
                ('ua_destino', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='solicitacoes_catalogo', to='dempam.infoua', verbose_name='UA Destino')),
            ],
            options={
                'verbose_name': 'Solicitação Catálogo',
                'verbose_name_plural': '13 - Solicitações Catálogo',
                'ordering': ['-data'],
            },
        ),
        migrations.CreateModel(
            name='ItemSolicitacaoCatalogo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('observacao', models.TextField(blank=True, verbose_name='Observação do Item')),
                ('bem_atribuido', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='atribuicoes_catalogo', to='dimrcbp.benspermanentes', verbose_name='Bem Atribuído')),
                ('catalogo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='itens_solicitados', to='dimrcbp.catalogo', verbose_name='Item do Catálogo')),
                ('solicitacao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens', to='dimrcbp.solicitacaocatalogo', verbose_name='Solicitação')),
            ],
            options={
                'verbose_name': 'Item Solicitação Catálogo',
                'verbose_name_plural': '14 - Itens Solicitação Catálogo',
            },
        ),
    ]
