# Generated by Django 6.0.2 on 2026-05-14 14:50

import dimrcbp.utils
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dimrcbp', '0016_solicitacaocatalogo_itemsolicitacaocatalogo'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Inventario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to=dimrcbp.utils.caminho_inventario, verbose_name='Foto do Inventário')),
                ('observation', models.TextField(blank=True, verbose_name='Observação do Inventário')),
                ('situation', models.CharField(choices=[('BOM', 'Bom'), ('REGULAR', 'Regular'), ('PRECARIO', 'Precário'), ('SUCATA', 'Sucata')], max_length=20, verbose_name='Situação no Inventário')),
                ('data_registro', models.DateTimeField(auto_now_add=True, verbose_name='Data do Registro')),
                ('bem', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='inventarios', to='dimrcbp.benspermanentes', verbose_name='Bem')),
                ('n_inventario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='n_inventarios', to='dimrcbp.periodoinventario', verbose_name='Período de Inventário')),
                ('registrado_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='registros_inventario', to=settings.AUTH_USER_MODEL, verbose_name='Registrado por')),
            ],
            options={
                'verbose_name': 'Registro de Inventário',
                'verbose_name_plural': '10 - Registros de Inventário',
                'ordering': ['-n_inventario__inicio', 'bem__tombo'],
                'constraints': [models.UniqueConstraint(fields=('n_inventario', 'bem'), name='unique_bem_por_inventario')],
            },
        ),
    ]
