# Generated by Django 6.0.2 on 2026-05-14 16:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dimrcbp', '0017_inventario'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historyuas',
            name='current_registration',
        ),
        migrations.RemoveField(
            model_name='historyuas',
            name='current_responsible',
        ),
        migrations.RemoveField(
            model_name='historyuas',
            name='last_registration',
        ),
        migrations.RemoveField(
            model_name='historyuas',
            name='last_responsible',
        ),
        migrations.RemoveField(
            model_name='historyuas',
            name='penultimate_registration',
        ),
        migrations.RemoveField(
            model_name='historyuas',
            name='penultimate_responsible',
        ),
    ]
