# Generated by Django 6.0.2 on 2026-05-26 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dimrcbp', '0018_remove_historyuas_current_registration_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='benspermanentes',
            name='acquisition_date',
            field=models.DateField(blank=True, null=True, verbose_name='Data da Aquisição'),
        ),
    ]
