# Generated by Django 6.0.2 on 2026-08-17 14:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dempam', '0011_setordempam_tipo'),
        ('dimrcbp', '0019_allow_null_acquisition_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='benspermanentes',
            name='locate',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='bens_permanentes', to='dempam.localizacaodempam', verbose_name='Localização (Pallet/Prateleira)'),
        ),
    ]
