# Generated by Django 6.0.2 on 2026-08-19 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dimrcbp', '0020_benspermanentes_locate'),
    ]

    operations = [
        migrations.AddField(
            model_name='useexternal',
            name='cpf_responsible',
            field=models.CharField(blank=True, max_length=14, verbose_name='CPF do Responsável pelo Uso Externo'),
        ),
    ]
