# Generated by Django 6.0.2 on 2026-08-20 15:17

import dimrcbp.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dimrcbp', '0021_useexternal_cpf_responsible'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventario',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to=dimrcbp.utils.caminho_inventario, verbose_name='Foto do Inventário'),
        ),
        migrations.AlterField(
            model_name='inventario',
            name='situation',
            field=models.CharField(choices=[('BOM', 'Bom'), ('REGULAR', 'Regular'), ('PRECARIO', 'Precário'), ('SUCATA', 'Sucata'), ('NAO_LOCALIZADO', 'Não Localizado')], max_length=20, verbose_name='Situação no Inventário'),
        ),
    ]
