# Generated by Django 6.0.2 on 2026-07-13 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ManutencaoAcesso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'permissions': [('access_manutencao', 'Pode acessar o módulo de Manutenção')],
                'managed': False,
                'default_permissions': (),
            },
        ),
    ]
