# Generated by Django 6.0.2 on 2026-07-13 18:10

import django.db.models.deletion
import manutencao.utils
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dempam', '0003_infoua_codigo_infoua_nivel_infoua_parent_and_more'),
        ('manutencao', '0002_grupo_manutencao'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EstoqueManutencao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('efisco', models.CharField(max_length=20, unique=True, verbose_name='E-Fisco')),
                ('descricao', models.TextField(verbose_name='Descrição')),
                ('medida', models.CharField(choices=[('METRO', 'Metro'), ('UNIDADE', 'Unidade'), ('QUILOGRAMA', 'Quilograma'), ('LITRO', 'Litro'), ('PACOTE', 'Pacote'), ('CAIXA', 'Caixa')], default='UNIDADE', max_length=20, verbose_name='Unidade de Medida')),
                ('grupo', models.CharField(choices=[('ELETRICA', 'Elétrica'), ('HIDRAULICA', 'Hidráulica'), ('MARCENARIA', 'Marcenaria'), ('PINTURA', 'Pintura'), ('REFRIGERACAO', 'Refrigeração'), ('SERRALHERIA', 'Serralheria'), ('ALVENARIA', 'Alvenaria'), ('FERRAMENTAS', 'Ferramentas'), ('EPI', 'EPI'), ('OUTROS', 'Outros')], default='OUTROS', max_length=20, verbose_name='Grupo')),
                ('mark', models.CharField(blank=True, max_length=40, verbose_name='Marca')),
                ('amount_shock', models.PositiveIntegerField(default=0, verbose_name='Quantidade')),
                ('validity', models.DateField(blank=True, null=True, verbose_name='Validade')),
                ('photo', models.ImageField(blank=True, null=True, upload_to=manutencao.utils.path_photo_bem_manutencao, verbose_name='Foto do Item')),
                ('form_input', models.CharField(blank=True, max_length=30, verbose_name='Forma de Entrada')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Data de Cadastro')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última modificação')),
                ('locate', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='localizacao_manutencao', to='dempam.localizacaodempam', verbose_name='Localização')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='estoque_manutencao_atualizado', to=settings.AUTH_USER_MODEL, verbose_name='Última edição por')),
            ],
            options={
                'verbose_name': 'Estoque de Manutenção',
                'verbose_name_plural': 'Estoque de Manutenção',
                'ordering': ['efisco'],
            },
        ),
    ]
